/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../providers/facebook-service';
import * as import4 from '../../providers/users-service';
import * as import5 from '../../providers/trips-subscriptions-service';
import * as import6 from './login';
import * as import7 from '@angular/core/src/linker/view_utils';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/linker/view_type';
import * as import10 from '@angular/core/src/change_detection/change_detection';
import * as import11 from '@angular/http/src/http';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from 'ionic-angular/navigation/nav-controller';
import * as import14 from 'ionic-angular/platform/platform';
import * as import15 from 'ionic-angular/components/loading/loading';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from 'ionic-angular/components/list/list';
import * as import21 from 'ionic-angular/components/item/item';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from 'ionic-angular/components/label/label';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
import * as import26 from 'ionic-angular/components/input/input';
import * as import27 from 'ionic-angular/components/checkbox/checkbox';
import * as import28 from 'ionic-angular/components/grid/grid';
import * as import29 from 'ionic-angular/components/button/button';
import * as import30 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import31 from 'ionic-angular/config/config';
import * as import32 from '@angular/core/src/linker/element_ref';
import * as import33 from 'ionic-angular/components/app/app';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/navigation/view-controller';
import * as import37 from 'ionic-angular/components/tabs/tabs';
import * as import38 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import39 from 'ionic-angular/components/toolbar/toolbar';
import * as import40 from 'ionic-angular/components/navbar/navbar';
import * as import41 from 'ionic-angular/gestures/gesture-controller';
import * as import42 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import43 from 'ionic-angular/util/form';
import * as import44 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import45 from '../../node_modules/ionic-angular/components/checkbox/checkbox.ngfactory';
import * as import46 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import47 from '@angular/forms/src/directives/ng_control';
import * as import48 from '@angular/forms/src/directives/control_value_accessor';
var renderType_LoginPage_Host:import0.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FacebookService_0_4:import3.FacebookService;
  _UsersService_0_5:import4.UsersService;
  _TripsSubscriptionsService_0_6:import5.TripsSubscriptionsService;
  _LoginPage_0_7:import6.LoginPage;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import9.ViewType.HOST,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FacebookService_0_4 = new import3.FacebookService();
    this._UsersService_0_5 = new import4.UsersService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._TripsSubscriptionsService_0_6 = new import5.TripsSubscriptionsService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._LoginPage_0_7 = new import6.LoginPage(this._FacebookService_0_4,this.parentInjector.get(import13.NavController),this.parentInjector.get(import14.Platform),this._UsersService_0_5,this.parentInjector.get(import15.LoadingController),this.parentInjector.get(import12.AlertController),this._TripsSubscriptionsService_0_6);
    this._appEl_0.initComponent(this._LoginPage_0_7,[],compView_0);
    compView_0.create(this._LoginPage_0_7,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.FacebookService) && (0 === requestNodeIndex))) { return this._FacebookService_0_4; }
    if (((token === import4.UsersService) && (0 === requestNodeIndex))) { return this._UsersService_0_5; }
    if (((token === import5.TripsSubscriptionsService) && (0 === requestNodeIndex))) { return this._TripsSubscriptionsService_0_6; }
    if (((token === import6.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_7; }
    return notFoundResult;
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,[],{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import17.ComponentFactory<import6.LoginPage> = new import17.ComponentFactory<import6.LoginPage>('ng-component',viewFactory_LoginPage_Host0,import6.LoginPage);
const styles_LoginPage:any[] = [];
var renderType_LoginPage:import0.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import6.LoginPage> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _Content_1_4:import18.Content;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _ToolbarTitle_7_4:import19.ToolbarTitle;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _List_14_3:import20.List;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _Item_16_4:import21.Item;
  _ItemContent_16_5:import21.ItemContent;
  _query_Label_16_0:import22.QueryList<any>;
  _query_Button_16_1:import22.QueryList<any>;
  _query_Icon_16_2:import22.QueryList<any>;
  _text_17:any;
  _el_18:any;
  _Label_18_3:import23.Label;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _NgModel_21_4:import24.NgModel;
  _NgControl_21_5:any;
  _NgControlStatus_21_6:import25.NgControlStatus;
  _TextInput_21_7:import26.TextInput;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _Item_24_4:import21.Item;
  _ItemContent_24_5:import21.ItemContent;
  _query_Label_24_0:import22.QueryList<any>;
  _query_Button_24_1:import22.QueryList<any>;
  _query_Icon_24_2:import22.QueryList<any>;
  _text_25:any;
  _el_26:any;
  _Label_26_3:import23.Label;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _NgModel_29_4:import24.NgModel;
  _NgControl_29_5:any;
  _NgControlStatus_29_6:import25.NgControlStatus;
  _TextInput_29_7:import26.TextInput;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _Item_32_4:import21.Item;
  _ItemContent_32_5:import21.ItemContent;
  _query_Label_32_0:import22.QueryList<any>;
  _query_Button_32_1:import22.QueryList<any>;
  _query_Icon_32_2:import22.QueryList<any>;
  _text_33:any;
  _el_34:any;
  _Label_34_3:import23.Label;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _Checkbox_37_4:import27.Checkbox;
  _NG_VALUE_ACCESSOR_37_5:any[];
  _NgModel_37_6:import24.NgModel;
  _NgControl_37_7:any;
  _NgControlStatus_37_8:import25.NgControlStatus;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _Grid_41_3:import28.Grid;
  _text_42:any;
  _el_43:any;
  _Row_43_3:import28.Row;
  _text_44:any;
  _el_45:any;
  _Col_45_3:import28.Col;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _Button_47_4:import29.Button;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _Col_51_3:import28.Col;
  _text_52:any;
  _el_53:any;
  /*private*/ _appEl_53:import2.AppElement;
  _Button_53_4:import29.Button;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _Row_58_3:import28.Row;
  _text_59:any;
  _el_60:any;
  _Col_60_3:import28.Col;
  _text_61:any;
  _el_62:any;
  /*private*/ _appEl_62:import2.AppElement;
  _Button_62_4:import29.Button;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_36:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import9.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','login-content');
    this.renderer.setElementAttribute(this._el_1,'padding','');
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import30.viewFactory_Content0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Content_1_4 = new import18.Content(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import33.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import36.ViewController,(null as any)),this.parentInjector.get(import37.Tabs,(null as any)));
    this._appEl_1.initComponent(this._Content_1_4,[],compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'style','text-align:center;height:45%;');
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'img',(null as any));
    this.renderer.setElementAttribute(this._el_5,'src','img/icon-l.png');
    this.renderer.setElementAttribute(this._el_5,'style','margin-top:5%;');
    this._text_6 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_3,'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_7,'style','margin-top:10px;');
    this._appEl_7 = new import2.AppElement(7,3,this,this._el_7);
    var compView_7:any = import38.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(7),this._appEl_7);
    this._ToolbarTitle_7_4 = new import19.ToolbarTitle(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_7),this.renderer,this.parentInjector.get(import39.Toolbar,(null as any)),this.parentInjector.get(import40.Navbar,(null as any)));
    this._appEl_7.initComponent(this._ToolbarTitle_7_4,[],compView_7);
    this._text_8 = this.renderer.createText((null as any),'Iniciar sesión',(null as any));
    compView_7.create(this._ToolbarTitle_7_4,[[].concat([this._text_8])],(null as any));
    this._text_9 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_3,'p',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'O registrarse.',(null as any));
    this._text_12 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_14_3 = new import20.List(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import41.GestureController));
    this._text_15 = this.renderer.createText(this._el_14,'\n\n  ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','item item-block');
    this.renderer.setElementAttribute(this._el_16,'style','opacity:0.8;');
    this._appEl_16 = new import2.AppElement(16,14,this,this._el_16);
    var compView_16:any = import42.viewFactory_Item0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Item_16_4 = new import21.Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_16),this.renderer);
    this._ItemContent_16_5 = new import21.ItemContent();
    this._query_Label_16_0 = new import22.QueryList<any>();
    this._query_Button_16_1 = new import22.QueryList<any>();
    this._query_Icon_16_2 = new import22.QueryList<any>();
    this._appEl_16.initComponent(this._Item_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_18,'floating','');
    this._Label_18_3 = new import23.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_18),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Usuario',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_21,'name','username');
    this.renderer.setElementAttribute(this._el_21,'type','text');
    this._appEl_21 = new import2.AppElement(21,16,this,this._el_21);
    var compView_21:any = import44.viewFactory_TextInput0(this.viewUtils,this.injector(21),this._appEl_21);
    this._NgModel_21_4 = new import24.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_21_5 = this._NgModel_21_4;
    this._NgControlStatus_21_6 = new import25.NgControlStatus(this._NgControl_21_5);
    this._TextInput_21_7 = new import26.TextInput(this.parentInjector.get(import31.Config),this.parentInjector.get(import43.Form),this._Item_16_4,this.parentInjector.get(import33.App),this.parentInjector.get(import14.Platform),new import32.ElementRef(this._el_21),this.renderer,this._Content_1_4,this.parentInjector.get(import13.NavController,(null as any)),this._NgControl_21_5);
    this._appEl_21.initComponent(this._TextInput_21_7,[],compView_21);
    compView_21.create(this._TextInput_21_7,[],(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_16_0.reset([this._Label_18_3]);
    this._Item_16_4.contentLabel = this._query_Label_16_0.first;
    compView_16.create(this._Item_16_4,[
      [],
      [].concat([this._el_18]),
      [].concat([
        this._text_17,
        this._text_20,
        this._text_22
      ]
      ),
      [].concat([this._el_21]),
      []
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText(this._el_14,'\n\n  ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_14,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item item-block');
    this.renderer.setElementAttribute(this._el_24,'style','opacity:0.8;');
    this._appEl_24 = new import2.AppElement(24,14,this,this._el_24);
    var compView_24:any = import42.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import21.Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_24),this.renderer);
    this._ItemContent_24_5 = new import21.ItemContent();
    this._query_Label_24_0 = new import22.QueryList<any>();
    this._query_Button_24_1 = new import22.QueryList<any>();
    this._query_Icon_24_2 = new import22.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4,[],compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_26,'floating','');
    this._Label_26_3 = new import23.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_26),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Contraseña',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_29,'name','password');
    this.renderer.setElementAttribute(this._el_29,'type','password');
    this._appEl_29 = new import2.AppElement(29,24,this,this._el_29);
    var compView_29:any = import44.viewFactory_TextInput0(this.viewUtils,this.injector(29),this._appEl_29);
    this._NgModel_29_4 = new import24.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_29_5 = this._NgModel_29_4;
    this._NgControlStatus_29_6 = new import25.NgControlStatus(this._NgControl_29_5);
    this._TextInput_29_7 = new import26.TextInput(this.parentInjector.get(import31.Config),this.parentInjector.get(import43.Form),this._Item_24_4,this.parentInjector.get(import33.App),this.parentInjector.get(import14.Platform),new import32.ElementRef(this._el_29),this.renderer,this._Content_1_4,this.parentInjector.get(import13.NavController,(null as any)),this._NgControl_29_5);
    this._appEl_29.initComponent(this._TextInput_29_7,[],compView_29);
    compView_29.create(this._TextInput_29_7,[],(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_24_0.reset([this._Label_26_3]);
    this._Item_24_4.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4,[
      [],
      [].concat([this._el_26]),
      [].concat([
        this._text_25,
        this._text_28,
        this._text_30
      ]
      ),
      [].concat([this._el_29]),
      []
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(this._el_14,'\n  ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_14,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','item item-block');
    this.renderer.setElementAttribute(this._el_32,'style','opacity:0.8;');
    this._appEl_32 = new import2.AppElement(32,14,this,this._el_32);
    var compView_32:any = import42.viewFactory_Item0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Item_32_4 = new import21.Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_32),this.renderer);
    this._ItemContent_32_5 = new import21.ItemContent();
    this._query_Label_32_0 = new import22.QueryList<any>();
    this._query_Button_32_1 = new import22.QueryList<any>();
    this._query_Icon_32_2 = new import22.QueryList<any>();
    this._appEl_32.initComponent(this._Item_32_4,[],compView_32);
    this._text_33 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_34_3 = new import23.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_34),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'Recordar mi usuario',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-checkbox',(null as any));
    this._appEl_37 = new import2.AppElement(37,32,this,this._el_37);
    var compView_37:any = import45.viewFactory_Checkbox0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Checkbox_37_4 = new import27.Checkbox(this.parentInjector.get(import31.Config),this.parentInjector.get(import43.Form),this._Item_32_4,new import32.ElementRef(this._el_37),this.renderer);
    this._NG_VALUE_ACCESSOR_37_5 = [this._Checkbox_37_4];
    this._NgModel_37_6 = new import24.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_37_5);
    this._NgControl_37_7 = this._NgModel_37_6;
    this._NgControlStatus_37_8 = new import25.NgControlStatus(this._NgControl_37_7);
    this._appEl_37.initComponent(this._Checkbox_37_4,[],compView_37);
    compView_37.create(this._Checkbox_37_4,[],(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_32_0.reset([this._Label_34_3]);
    this._Item_32_4.contentLabel = this._query_Label_32_0.first;
    compView_32.create(this._Item_32_4,[
      [].concat([this._el_37]),
      [].concat([this._el_34]),
      [].concat([
        this._text_33,
        this._text_36,
        this._text_38
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_39 = this.renderer.createText(this._el_14,'\n\n',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_41_3 = new import28.Grid();
    this._text_42 = this.renderer.createText(this._el_41,'\n  ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'ion-row',(null as any));
    this._Row_43_3 = new import28.Row();
    this._text_44 = this.renderer.createText(this._el_43,'\n    ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_45,'width-50','');
    this._Col_45_3 = new import28.Col();
    this._text_46 = this.renderer.createText(this._el_45,'\n      ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'button',(null as any));
    this.renderer.setElementAttribute(this._el_47,'block','');
    this.renderer.setElementAttribute(this._el_47,'ion-button','');
    this._appEl_47 = new import2.AppElement(47,45,this,this._el_47);
    var compView_47:any = import46.viewFactory_Button0(this.viewUtils,this.injector(47),this._appEl_47);
    this._Button_47_4 = new import29.Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_47),this.renderer);
    this._appEl_47.initComponent(this._Button_47_4,[],compView_47);
    this._text_48 = this.renderer.createText((null as any),'Ingresar',(null as any));
    compView_47.create(this._Button_47_4,[[].concat([this._text_48])],(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_43,'\n    ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_43,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_51,'style','text-align:center;');
    this.renderer.setElementAttribute(this._el_51,'width-50','');
    this._Col_51_3 = new import28.Col();
    this._text_52 = this.renderer.createText(this._el_51,'\n      ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'button',(null as any));
    this.renderer.setElementAttribute(this._el_53,'clear','');
    this.renderer.setElementAttribute(this._el_53,'ion-button','');
    this._appEl_53 = new import2.AppElement(53,51,this,this._el_53);
    var compView_53:any = import46.viewFactory_Button0(this.viewUtils,this.injector(53),this._appEl_53);
    this._Button_53_4 = new import29.Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_53),this.renderer);
    this._appEl_53.initComponent(this._Button_53_4,[],compView_53);
    this._text_54 = this.renderer.createText((null as any),'Registrarse',(null as any));
    compView_53.create(this._Button_53_4,[[].concat([this._text_54])],(null as any));
    this._text_55 = this.renderer.createText(this._el_51,'\n    ',(null as any));
    this._text_56 = this.renderer.createText(this._el_43,'\n  ',(null as any));
    this._text_57 = this.renderer.createText(this._el_41,'\n  ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_41,'ion-row',(null as any));
    this._Row_58_3 = new import28.Row();
    this._text_59 = this.renderer.createText(this._el_58,'\n    ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_58,'ion-col',(null as any));
    this._Col_60_3 = new import28.Col();
    this._text_61 = this.renderer.createText(this._el_60,'\n      ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'button',(null as any));
    this.renderer.setElementAttribute(this._el_62,'block','');
    this.renderer.setElementAttribute(this._el_62,'ion-button','');
    this._appEl_62 = new import2.AppElement(62,60,this,this._el_62);
    var compView_62:any = import46.viewFactory_Button0(this.viewUtils,this.injector(62),this._appEl_62);
    this._Button_62_4 = new import29.Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_62),this.renderer);
    this._appEl_62.initComponent(this._Button_62_4,[],compView_62);
    this._text_63 = this.renderer.createText((null as any),'Ingresar con Facebook',(null as any));
    compView_62.create(this._Button_62_4,[[].concat([this._text_63])],(null as any));
    this._text_64 = this.renderer.createText(this._el_60,'\n    ',(null as any));
    this._text_65 = this.renderer.createText(this._el_58,'\n    \n  ',(null as any));
    this._text_66 = this.renderer.createText(this._el_41,'\n',(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    compView_1.create(this._Content_1_4,[
      [],
      [].concat([
        this._text_2,
        this._el_3,
        this._text_13,
        this._el_14,
        this._text_40,
        this._el_41,
        this._text_67
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_68 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import10.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_21,'ngModelChange',this.eventHandler(this._handle_ngModelChange_21_0.bind(this)));
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    const subscription_0:any = this._NgModel_21_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_21_0.bind(this)));
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
    this._expr_8 = import10.UNINITIALIZED;
    this._expr_9 = import10.UNINITIALIZED;
    this._expr_10 = import10.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_29,'ngModelChange',this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    this._expr_12 = import10.UNINITIALIZED;
    this._expr_13 = import10.UNINITIALIZED;
    const subscription_1:any = this._NgModel_29_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_29_0.bind(this)));
    this._expr_14 = import10.UNINITIALIZED;
    this._expr_15 = import10.UNINITIALIZED;
    this._expr_16 = import10.UNINITIALIZED;
    this._expr_17 = import10.UNINITIALIZED;
    this._expr_18 = import10.UNINITIALIZED;
    this._expr_19 = import10.UNINITIALIZED;
    this._expr_20 = import10.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_37,'ngModelChange',this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_1.bind(this)));
    this._expr_23 = import10.UNINITIALIZED;
    this._expr_24 = import10.UNINITIALIZED;
    const subscription_2:any = this._NgModel_37_6.update.subscribe(this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    this._expr_25 = import10.UNINITIALIZED;
    this._expr_26 = import10.UNINITIALIZED;
    this._expr_27 = import10.UNINITIALIZED;
    this._expr_28 = import10.UNINITIALIZED;
    this._expr_29 = import10.UNINITIALIZED;
    this._expr_30 = import10.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_0.bind(this)));
    this._expr_32 = import10.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_53,'click',this.eventHandler(this._handle_click_53_0.bind(this)));
    this._expr_34 = import10.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_62,'click',this.eventHandler(this._handle_click_62_0.bind(this)));
    this._expr_36 = import10.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.ToolbarTitle) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarTitle_7_4; }
    if (((token === import23.Label) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Label_18_3; }
    if (((token === import24.NgModel) && (21 === requestNodeIndex))) { return this._NgModel_21_4; }
    if (((token === import47.NgControl) && (21 === requestNodeIndex))) { return this._NgControl_21_5; }
    if (((token === import25.NgControlStatus) && (21 === requestNodeIndex))) { return this._NgControlStatus_21_6; }
    if (((token === import26.TextInput) && (21 === requestNodeIndex))) { return this._TextInput_21_7; }
    if (((token === import21.Item) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Item_16_4; }
    if (((token === import21.ItemContent) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ItemContent_16_5; }
    if (((token === import23.Label) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Label_26_3; }
    if (((token === import24.NgModel) && (29 === requestNodeIndex))) { return this._NgModel_29_4; }
    if (((token === import47.NgControl) && (29 === requestNodeIndex))) { return this._NgControl_29_5; }
    if (((token === import25.NgControlStatus) && (29 === requestNodeIndex))) { return this._NgControlStatus_29_6; }
    if (((token === import26.TextInput) && (29 === requestNodeIndex))) { return this._TextInput_29_7; }
    if (((token === import21.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Item_24_4; }
    if (((token === import21.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ItemContent_24_5; }
    if (((token === import23.Label) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Label_34_3; }
    if (((token === import27.Checkbox) && (37 === requestNodeIndex))) { return this._Checkbox_37_4; }
    if (((token === import48.NG_VALUE_ACCESSOR) && (37 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_37_5; }
    if (((token === import24.NgModel) && (37 === requestNodeIndex))) { return this._NgModel_37_6; }
    if (((token === import47.NgControl) && (37 === requestNodeIndex))) { return this._NgControl_37_7; }
    if (((token === import25.NgControlStatus) && (37 === requestNodeIndex))) { return this._NgControlStatus_37_8; }
    if (((token === import21.Item) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Item_32_4; }
    if (((token === import21.ItemContent) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ItemContent_32_5; }
    if (((token === import20.List) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._List_14_3; }
    if (((token === import29.Button) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Button_47_4; }
    if (((token === import28.Col) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Col_45_3; }
    if (((token === import29.Button) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Button_53_4; }
    if (((token === import28.Col) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Col_51_3; }
    if (((token === import28.Row) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Row_43_3; }
    if (((token === import29.Button) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Button_62_4; }
    if (((token === import28.Col) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Col_60_3; }
    if (((token === import28.Row) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Row_58_3; }
    if (((token === import28.Grid) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Grid_41_3; }
    if (((token === import18.Content) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Content_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import10.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_1_4.ngOnInit(); }
    changes = (null as any);
    const currVal_2:any = 'username';
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgModel_21_4.name = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import10.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.data.username;
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgModel_21_4.model = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import10.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgModel_21_4.ngOnChanges(changes); }
    const currVal_10:any = 'text';
    if (import7.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._TextInput_21_7.type = currVal_10;
      this._expr_10 = currVal_10;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_21_7.ngOnInit(); }
    changes = (null as any);
    const currVal_12:any = 'password';
    if (import7.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgModel_29_4.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import10.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this.context.data.password;
    if (import7.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgModel_29_4.model = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import10.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgModel_29_4.ngOnChanges(changes); }
    const currVal_20:any = 'password';
    if (import7.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._TextInput_29_7.type = currVal_20;
      this._expr_20 = currVal_20;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_29_7.ngOnInit(); }
    changes = (null as any);
    const currVal_24:any = this.context.rememberMe;
    if (import7.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._NgModel_37_6.model = currVal_24;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import10.SimpleChange(this._expr_24,currVal_24);
      this._expr_24 = currVal_24;
    }
    if ((changes !== (null as any))) { this._NgModel_37_6.ngOnChanges(changes); }
    changed = false;
    const currVal_32:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._Button_47_4.block = currVal_32;
      changed = true;
      this._expr_32 = currVal_32;
    }
    if (changed) { this._appEl_47.componentView.markAsCheckOnce(); }
    changed = false;
    const currVal_34:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._Button_53_4.clear = currVal_34;
      changed = true;
      this._expr_34 = currVal_34;
    }
    if (changed) { this._appEl_53.componentView.markAsCheckOnce(); }
    changed = false;
    const currVal_36:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._Button_62_4.block = currVal_36;
      changed = true;
      this._expr_36 = currVal_36;
    }
    if (changed) { this._appEl_62.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_16_1.dirty) {
        this._query_Button_16_1.reset([]);
        this._Item_16_4._buttons = this._query_Button_16_1;
        this._query_Button_16_1.notifyOnChanges();
      }
      if (this._query_Icon_16_2.dirty) {
        this._query_Icon_16_2.reset([]);
        this._Item_16_4._icons = this._query_Icon_16_2;
        this._query_Icon_16_2.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset([]);
        this._Item_24_4._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset([]);
        this._Item_24_4._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_32_1.dirty) {
        this._query_Button_32_1.reset([]);
        this._Item_32_4._buttons = this._query_Button_32_1;
        this._query_Button_32_1.notifyOnChanges();
      }
      if (this._query_Icon_32_2.dirty) {
        this._query_Icon_32_2.reset([]);
        this._Item_32_4._icons = this._query_Icon_32_2;
        this._query_Icon_32_2.notifyOnChanges();
      }
      this._TextInput_21_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_16_4.ngAfterContentInit(); }
      this._TextInput_29_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_24_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Checkbox_37_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_32_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_47_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_53_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_62_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_1_4._sbPadding;
    if (import7.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_1,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_4:any = this._NgControlStatus_21_6.ngClassUntouched;
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_21,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatus_21_6.ngClassTouched;
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_21,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_21_6.ngClassPristine;
    if (import7.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_21,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_21_6.ngClassDirty;
    if (import7.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_21,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_21_6.ngClassValid;
    if (import7.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_21,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_21_6.ngClassInvalid;
    if (import7.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_21,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_14:any = this._NgControlStatus_29_6.ngClassUntouched;
    if (import7.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_29,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_29_6.ngClassTouched;
    if (import7.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_29,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_29_6.ngClassPristine;
    if (import7.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_29,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_29_6.ngClassDirty;
    if (import7.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_29,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_29_6.ngClassValid;
    if (import7.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_29,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_29_6.ngClassInvalid;
    if (import7.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_29,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_23:any = this._Checkbox_37_4._disabled;
    if (import7.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_37,'checkbox-disabled',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_25:any = this._NgControlStatus_37_8.ngClassUntouched;
    if (import7.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_37,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_37_8.ngClassTouched;
    if (import7.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_37,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_37_8.ngClassPristine;
    if (import7.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_37,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_37_8.ngClassDirty;
    if (import7.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_37,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_37_8.ngClassValid;
    if (import7.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_37,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_37_8.ngClassInvalid;
    if (import7.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_37,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_21_4.ngOnDestroy();
    this._TextInput_21_7.ngOnDestroy();
    this._NgModel_29_4.ngOnDestroy();
    this._TextInput_29_7.ngOnDestroy();
    this._Checkbox_37_4.ngOnDestroy();
    this._NgModel_37_6.ngOnDestroy();
    this._Content_1_4.ngOnDestroy();
  }
  private _handle_ngModelChange_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.data.username = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.data.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.rememberMe = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_1($event:any):boolean {
    this._appEl_37.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Checkbox_37_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.defaultLogin()) !== false);
    return (true && pd_0);
  }
  private _handle_click_53_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.register()) !== false);
    return (true && pd_0);
  }
  private _handle_click_62_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.facebookLogin()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<import6.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('/home/nicolas/projects/cloudtripper/cloudtripper-frontend/.tmp/pages/login/login.html',0,import16.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}