/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../providers/logs-service';
import * as import4 from './trip-details';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from 'ionic-angular/navigation/nav-params';
import * as import13 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import14 from '../../providers/trips-subscriptions-service';
import * as import15 from 'ionic-angular/components/loading/loading';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from 'ionic-angular/components/toolbar/toolbar';
import * as import20 from 'ionic-angular/components/navbar/navbar';
import * as import21 from '@angular/common/src/directives/ng_if';
import * as import22 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import23 from 'ionic-angular/components/content/content';
import * as import24 from 'ionic-angular/components/item/item';
import * as import25 from 'ionic-angular/components/list/list-header';
import * as import26 from 'ionic-angular/components/icon/icon';
import * as import27 from 'ionic-angular/components/button/button';
import * as import28 from 'ionic-angular/components/list/list';
import * as import29 from '@angular/common/src/directives/ng_for';
import * as import30 from 'ionic-angular/config/config';
import * as import31 from '@angular/core/src/linker/element_ref';
import * as import32 from 'ionic-angular/navigation/view-controller';
import * as import33 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import34 from 'ionic-angular/components/app/app';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import37 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import38 from 'ionic-angular/util/keyboard';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from 'ionic-angular/components/tabs/tabs';
import * as import41 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import42 from 'ionic-angular/util/form';
import * as import43 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import44 from 'ionic-angular/gestures/gesture-controller';
import * as import45 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import46 from '@angular/core/src/security';
import * as import47 from 'ionic-angular/components/menu/menu-toggle';
import * as import48 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import49 from 'ionic-angular/components/menu/menu-controller';
import * as import50 from 'ionic-angular/components/item/item-sliding';
import * as import51 from 'ionic-angular/components/avatar/avatar';
import * as import52 from '../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
var renderType_TripDetailsPage_Host:import0.RenderComponentType = (null as any);
class _View_TripDetailsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LogsService_0_4:import3.LogsService;
  _TripDetailsPage_0_5:import4.TripDetailsPage;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_TripDetailsPage_Host0,renderType_TripDetailsPage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TripDetailsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LogsService_0_4 = new import3.LogsService(this.parentInjector.get(import9.Http),this.parentInjector.get(import10.AlertController));
    this._TripDetailsPage_0_5 = new import4.TripDetailsPage(this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.NavParams),this._LogsService_0_4,this.parentInjector.get(import13.DomSanitizer),this.parentInjector.get(import14.TripsSubscriptionsService),this.parentInjector.get(import15.LoadingController));
    this._appEl_0.initComponent(this._TripDetailsPage_0_5,[],compView_0);
    compView_0.create(this._TripDetailsPage_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LogsService) && (0 === requestNodeIndex))) { return this._LogsService_0_4; }
    if (((token === import4.TripDetailsPage) && (0 === requestNodeIndex))) { return this._TripDetailsPage_0_5; }
    return notFoundResult;
  }
}
function viewFactory_TripDetailsPage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TripDetailsPage_Host === (null as any))) { (renderType_TripDetailsPage_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,[],{})); }
  return new _View_TripDetailsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const TripDetailsPageNgFactory:import17.ComponentFactory<import4.TripDetailsPage> = new import17.ComponentFactory<import4.TripDetailsPage>('ng-component',viewFactory_TripDetailsPage_Host0,import4.TripDetailsPage);
const styles_TripDetailsPage:any[] = [];
var renderType_TripDetailsPage:import0.RenderComponentType = (null as any);
class _View_TripDetailsPage0 extends import1.AppView<import4.TripDetailsPage> {
  _viewQuery_map_0:import18.QueryList<any>;
  _el_0:any;
  _Header_0_3:import19.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import20.Navbar;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import21.NgIf;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _ToolbarTitle_6_4:import22.ToolbarTitle;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _Content_11_4:import23.Content;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _ItemGroup_26_3:import24.ItemGroup;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _Item_28_4:import24.Item;
  _ListHeader_28_5:import25.ListHeader;
  _query_Label_28_0:import18.QueryList<any>;
  _query_Button_28_1:import18.QueryList<any>;
  _query_Icon_28_2:import18.QueryList<any>;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _Item_31_4:import24.Item;
  _ItemContent_31_5:import24.ItemContent;
  _query_Label_31_0:import18.QueryList<any>;
  _query_Button_31_1:import18.QueryList<any>;
  _query_Icon_31_2:import18.QueryList<any>;
  _text_32:any;
  _el_33:any;
  _Icon_33_3:import26.Icon;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import2.AppElement;
  _Item_36_4:import24.Item;
  _ItemContent_36_5:import24.ItemContent;
  _query_Label_36_0:import18.QueryList<any>;
  _query_Button_36_1:import18.QueryList<any>;
  _query_Icon_36_2:import18.QueryList<any>;
  _text_37:any;
  _el_38:any;
  _Icon_38_3:import26.Icon;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _Item_41_4:import24.Item;
  _ItemContent_41_5:import24.ItemContent;
  _query_Label_41_0:import18.QueryList<any>;
  _query_Button_41_1:import18.QueryList<any>;
  _query_Icon_41_2:import18.QueryList<any>;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import2.AppElement;
  _Button_43_4:import27.Button;
  _text_44:any;
  _el_45:any;
  _Icon_45_3:import26.Icon;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _List_54_3:import28.List;
  _text_55:any;
  _el_56:any;
  /*private*/ _appEl_56:import2.AppElement;
  _Item_56_4:import24.Item;
  _ListHeader_56_5:import25.ListHeader;
  _query_Label_56_0:import18.QueryList<any>;
  _query_Button_56_1:import18.QueryList<any>;
  _query_Icon_56_2:import18.QueryList<any>;
  _text_57:any;
  _text_58:any;
  _anchor_59:any;
  /*private*/ _appEl_59:import2.AppElement;
  _TemplateRef_59_5:any;
  _NgFor_59_6:import29.NgFor;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_TripDetailsPage0,renderType_TripDetailsPage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_map_0 = new import18.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import19.Header(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import32.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import33.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import20.Navbar(this.parentInjector.get(import34.App),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import35.TemplateRef_(this._appEl_4,viewFactory_TripDetailsPage1);
    this._NgIf_4_6 = new import21.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_6 = new import2.AppElement(6,2,this,this._el_6);
    var compView_6:any = import36.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(6),this._appEl_6);
    this._ToolbarTitle_6_4 = new import22.ToolbarTitle(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import19.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_6.initComponent(this._ToolbarTitle_6_4,[],compView_6);
    this._text_7 = this.renderer.createText((null as any),'Detalles de viaje',(null as any));
    compView_6.create(this._ToolbarTitle_6_4,[[].concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._appEl_4]),
      [],
      [],
      [].concat([
        this._text_3,
        this._text_5,
        this._el_6,
        this._text_8
      ]
      )
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_11 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_11 = new import2.AppElement(11,(null as any),this,this._el_11);
    var compView_11:any = import37.viewFactory_Content0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Content_11_4 = new import23.Content(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import34.App),this.parentInjector.get(import38.Keyboard),this.parentInjector.get(import39.NgZone),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import40.Tabs,(null as any)));
    this._appEl_11.initComponent(this._Content_11_4,[],compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n\n  ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','title-background');
    this.renderer.setElementAttribute(this._el_14,'item-content','');
    this._text_15 = this.renderer.createText(this._el_14,'      \n    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','title-div');
    this.renderer.setElementAttribute(this._el_16,'style','height:200px;width:100%;overflow:hidden;');
    this._text_17 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'img',(null as any));
    this._text_19 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','title-name');
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_23 = this.renderer.createText(this._el_14,'\n      \n  ',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n    \n  ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-item-group',(null as any));
    this._ItemGroup_26_3 = new import24.ItemGroup();
    this._text_27 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','item');
    this._appEl_28 = new import2.AppElement(28,26,this,this._el_28);
    var compView_28:any = import41.viewFactory_Item0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Item_28_4 = new import24.Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_28),this.renderer);
    this._ListHeader_28_5 = new import25.ListHeader(this.parentInjector.get(import30.Config),this.renderer,new import31.ElementRef(this._el_28),(null as any));
    this._query_Label_28_0 = new import18.QueryList<any>();
    this._query_Button_28_1 = new import18.QueryList<any>();
    this._query_Icon_28_2 = new import18.QueryList<any>();
    this._appEl_28.initComponent(this._Item_28_4,[],compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n      Datos\n    ',(null as any));
    this._query_Label_28_0.reset([]);
    this._Item_28_4.contentLabel = this._query_Label_28_0.first;
    compView_28.create(this._Item_28_4,[
      [],
      [],
      [].concat([this._text_29]),
      [],
      []
    ]
    ,(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_26,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','item item-block');
    this.renderer.setElementAttribute(this._el_31,'text-wrap','');
    this._appEl_31 = new import2.AppElement(31,26,this,this._el_31);
    var compView_31:any = import41.viewFactory_Item0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Item_31_4 = new import24.Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_31),this.renderer);
    this._ItemContent_31_5 = new import24.ItemContent();
    this._query_Label_31_0 = new import18.QueryList<any>();
    this._query_Button_31_1 = new import18.QueryList<any>();
    this._query_Icon_31_2 = new import18.QueryList<any>();
    this._appEl_31.initComponent(this._Item_31_4,[],compView_31);
    this._text_32 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_33,'item-left','');
    this.renderer.setElementAttribute(this._el_33,'name','plane');
    this.renderer.setElementAttribute(this._el_33,'role','img');
    this._Icon_33_3 = new import26.Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_33),this.renderer);
    this._text_34 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_31_0.reset([]);
    this._Item_31_4.contentLabel = this._query_Label_31_0.first;
    compView_31.create(this._Item_31_4,[
      [].concat([this._el_33]),
      [],
      [].concat([
        this._text_32,
        this._text_34
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_26,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','item item-block');
    this.renderer.setElementAttribute(this._el_36,'text-wrap','');
    this._appEl_36 = new import2.AppElement(36,26,this,this._el_36);
    var compView_36:any = import41.viewFactory_Item0(this.viewUtils,this.injector(36),this._appEl_36);
    this._Item_36_4 = new import24.Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_36),this.renderer);
    this._ItemContent_36_5 = new import24.ItemContent();
    this._query_Label_36_0 = new import18.QueryList<any>();
    this._query_Button_36_1 = new import18.QueryList<any>();
    this._query_Icon_36_2 = new import18.QueryList<any>();
    this._appEl_36.initComponent(this._Item_36_4,[],compView_36);
    this._text_37 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_38,'item-left','');
    this.renderer.setElementAttribute(this._el_38,'name','calendar');
    this.renderer.setElementAttribute(this._el_38,'role','img');
    this._Icon_38_3 = new import26.Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_38),this.renderer);
    this._text_39 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_36_0.reset([]);
    this._Item_36_4.contentLabel = this._query_Label_36_0.first;
    compView_36.create(this._Item_36_4,[
      [].concat([this._el_38]),
      [],
      [].concat([
        this._text_37,
        this._text_39
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_26,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','item item-block');
    this._appEl_41 = new import2.AppElement(41,26,this,this._el_41);
    var compView_41:any = import41.viewFactory_Item0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Item_41_4 = new import24.Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_41),this.renderer);
    this._ItemContent_41_5 = new import24.ItemContent();
    this._query_Label_41_0 = new import18.QueryList<any>();
    this._query_Button_41_1 = new import18.QueryList<any>();
    this._query_Icon_41_2 = new import18.QueryList<any>();
    this._appEl_41.initComponent(this._Item_41_4,[],compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_43,'block','');
    this.renderer.setElementAttribute(this._el_43,'color','primary');
    this.renderer.setElementAttribute(this._el_43,'icon-left','');
    this.renderer.setElementAttribute(this._el_43,'ion-button','');
    this.renderer.setElementAttribute(this._el_43,'small','');
    this._appEl_43 = new import2.AppElement(43,41,this,this._el_43);
    var compView_43:any = import43.viewFactory_Button0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Button_43_4 = new import27.Button((null as any),'',this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_43),this.renderer);
    this._appEl_43.initComponent(this._Button_43_4,[],compView_43);
    this._text_44 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_45,'name','image');
    this.renderer.setElementAttribute(this._el_45,'role','img');
    this._Icon_45_3 = new import26.Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_45),this.renderer);
    this._text_46 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Ver imágenes',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_43.create(this._Button_43_4,[[].concat([
        this._text_44,
        this._el_45,
        this._text_46,
        this._el_47,
        this._text_49
      ]
    )],(null as any));
    this._text_50 = this.renderer.createText((null as any),' \n    ',(null as any));
    this._query_Label_41_0.reset([]);
    this._Item_41_4.contentLabel = this._query_Label_41_0.first;
    compView_41.create(this._Item_41_4,[
      [],
      [],
      [].concat([
        this._text_42,
        this._el_43,
        this._text_50
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_51 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._text_52 = this.renderer.createText(this._el_26,'\n  ',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_54_3 = new import28.List(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_54),this.renderer,this.parentInjector.get(import44.GestureController));
    this._text_55 = this.renderer.createText(this._el_54,'\n    ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','item');
    this._appEl_56 = new import2.AppElement(56,54,this,this._el_56);
    var compView_56:any = import41.viewFactory_Item0(this.viewUtils,this.injector(56),this._appEl_56);
    this._Item_56_4 = new import24.Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_56),this.renderer);
    this._ListHeader_56_5 = new import25.ListHeader(this.parentInjector.get(import30.Config),this.renderer,new import31.ElementRef(this._el_56),(null as any));
    this._query_Label_56_0 = new import18.QueryList<any>();
    this._query_Button_56_1 = new import18.QueryList<any>();
    this._query_Icon_56_2 = new import18.QueryList<any>();
    this._appEl_56.initComponent(this._Item_56_4,[],compView_56);
    this._text_57 = this.renderer.createText((null as any),'\n      Subscriptores\n    ',(null as any));
    this._query_Label_56_0.reset([]);
    this._Item_56_4.contentLabel = this._query_Label_56_0.first;
    compView_56.create(this._Item_56_4,[
      [],
      [],
      [].concat([this._text_57]),
      [],
      []
    ]
    ,(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n    ',(null as any));
    this._anchor_59 = this.renderer.createTemplateAnchor(this._el_54,(null as any));
    this._appEl_59 = new import2.AppElement(59,54,this,this._anchor_59);
    this._TemplateRef_59_5 = new import35.TemplateRef_(this._appEl_59,viewFactory_TripDetailsPage2);
    this._NgFor_59_6 = new import29.NgFor(this._appEl_59.vcRef,this._TemplateRef_59_5,this.parentInjector.get(import45.IterableDiffers),this.ref);
    this._text_60 = this.renderer.createText(this._el_54,' \n  ',(null as any));
    this._text_61 = this.renderer.createText((null as any),'\n',(null as any));
    compView_11.create(this._Content_11_4,[
      [],
      [].concat([
        this._text_12,
        this._text_13,
        this._el_14,
        this._text_24,
        this._text_25,
        this._el_26,
        this._text_53,
        this._el_54,
        this._text_61
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_43,'click',this.eventHandler(this._handle_click_43_0.bind(this)));
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._viewQuery_map_0.reset([]);
    this.context.mapElement = this._viewQuery_map_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._anchor_59,
      this._text_60,
      this._text_61,
      this._text_62
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import35.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import21.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import22.ToolbarTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarTitle_6_4; }
    if (((token === import20.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Navbar_2_4; }
    if (((token === import19.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Header_0_3; }
    if (((token === import24.Item) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Item_28_4; }
    if (((token === import25.ListHeader) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ListHeader_28_5; }
    if (((token === import26.Icon) && (33 === requestNodeIndex))) { return this._Icon_33_3; }
    if (((token === import24.Item) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_31_4; }
    if (((token === import24.ItemContent) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_31_5; }
    if (((token === import26.Icon) && (38 === requestNodeIndex))) { return this._Icon_38_3; }
    if (((token === import24.Item) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Item_36_4; }
    if (((token === import24.ItemContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ItemContent_36_5; }
    if (((token === import26.Icon) && (45 === requestNodeIndex))) { return this._Icon_45_3; }
    if (((token === import27.Button) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Button_43_4; }
    if (((token === import24.Item) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Item_41_4; }
    if (((token === import24.ItemContent) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._ItemContent_41_5; }
    if (((token === import24.ItemGroup) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._ItemGroup_26_3; }
    if (((token === import24.Item) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Item_56_4; }
    if (((token === import25.ListHeader) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._ListHeader_56_5; }
    if (((token === import35.TemplateRef) && (59 === requestNodeIndex))) { return this._TemplateRef_59_5; }
    if (((token === import29.NgFor) && (59 === requestNodeIndex))) { return this._NgFor_59_6; }
    if (((token === import28.List) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._List_54_3; }
    if (((token === import23.Content) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Content_11_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const currVal_2:boolean = !this.context.selectedTrip;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_4_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_11_4.ngOnInit(); }
    const currVal_6:any = 'plane';
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Icon_33_3.name = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = 'calendar';
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Icon_38_3.name = currVal_9;
      this._expr_9 = currVal_9;
    }
    changed = false;
    const currVal_13:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Button_43_4.small = currVal_13;
      changed = true;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._Button_43_4.block = currVal_14;
      changed = true;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = 'primary';
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Button_43_4.color = currVal_15;
      changed = true;
      this._expr_15 = currVal_15;
    }
    if (changed) { this._appEl_43.componentView.markAsCheckOnce(); }
    const currVal_16:any = 'image';
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Icon_45_3.name = currVal_16;
      this._expr_16 = currVal_16;
    }
    changes = (null as any);
    const currVal_18:any = this.context.subscriptors;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._NgFor_59_6.ngForOf = currVal_18;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_18,currVal_18);
      this._expr_18 = currVal_18;
    }
    if ((changes !== (null as any))) { this._NgFor_59_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_59_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_28_1.dirty) {
        this._query_Button_28_1.reset([]);
        this._Item_28_4._buttons = this._query_Button_28_1;
        this._query_Button_28_1.notifyOnChanges();
      }
      if (this._query_Icon_28_2.dirty) {
        this._query_Icon_28_2.reset([]);
        this._Item_28_4._icons = this._query_Icon_28_2;
        this._query_Icon_28_2.notifyOnChanges();
      }
      if (this._query_Button_31_1.dirty) {
        this._query_Button_31_1.reset([]);
        this._Item_31_4._buttons = this._query_Button_31_1;
        this._query_Button_31_1.notifyOnChanges();
      }
      if (this._query_Icon_31_2.dirty) {
        this._query_Icon_31_2.reset([this._Icon_33_3]);
        this._Item_31_4._icons = this._query_Icon_31_2;
        this._query_Icon_31_2.notifyOnChanges();
      }
      if (this._query_Button_36_1.dirty) {
        this._query_Button_36_1.reset([]);
        this._Item_36_4._buttons = this._query_Button_36_1;
        this._query_Button_36_1.notifyOnChanges();
      }
      if (this._query_Icon_36_2.dirty) {
        this._query_Icon_36_2.reset([this._Icon_38_3]);
        this._Item_36_4._icons = this._query_Icon_36_2;
        this._query_Icon_36_2.notifyOnChanges();
      }
      if (this._query_Button_41_1.dirty) {
        this._query_Button_41_1.reset([this._Button_43_4]);
        this._Item_41_4._buttons = this._query_Button_41_1;
        this._query_Button_41_1.notifyOnChanges();
      }
      if (this._query_Icon_41_2.dirty) {
        this._query_Icon_41_2.reset([]);
        this._Item_41_4._icons = this._query_Icon_41_2;
        this._query_Icon_41_2.notifyOnChanges();
      }
      if (this._query_Button_56_1.dirty) {
        this._query_Button_56_1.reset([]);
        this._Item_56_4._buttons = this._query_Button_56_1;
        this._query_Button_56_1.notifyOnChanges();
      }
      if (this._query_Icon_56_2.dirty) {
        this._query_Icon_56_2.reset([]);
        this._Item_56_4._icons = this._query_Icon_56_2;
        this._query_Icon_56_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_28_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_31_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_36_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_43_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_41_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_56_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = this._Content_11_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_11,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.selectedTrip.Image;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_18,'src',this.viewUtils.sanitizer.sanitize(import46.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import5.interpolate(1,'\n        ',this.context.selectedTrip.Destination,'\n      ');
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_21,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_33_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_33,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import5.interpolate(2,'\n        ',this.context.selectedTrip.Origin,' hacia ',this.context.selectedTrip.Destination,' \n    ');
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_34,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_10:any = this._Icon_38_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_38,'hide',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = import5.interpolate(2,'\n        ',this.context.selectedTrip.StartDate.toLocaleString(),' a ',this.context.selectedTrip.EndDate.toLocaleString(),' \n    ');
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_39,currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_17:any = this._Icon_45_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_45,'hide',currVal_17);
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_33_3.ngOnDestroy();
    this._Icon_38_3.ngOnDestroy();
    this._Icon_45_3.ngOnDestroy();
    this._Content_11_4.ngOnDestroy();
  }
  private _handle_click_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.showTripPhotos()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TripDetailsPage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.TripDetailsPage> {
  if ((renderType_TripDetailsPage === (null as any))) { (renderType_TripDetailsPage = viewUtils.createRenderComponentType('/home/nicolas/projects/cloudtripper/cloudtripper-frontend/.tmp/pages/trip-details/trip-details.html',0,import16.ViewEncapsulation.None,styles_TripDetailsPage,{})); }
  return new _View_TripDetailsPage0(viewUtils,parentInjector,declarationEl);
}
class _View_TripDetailsPage1 extends import1.AppView<any> {
  _el_0:any;
  _MenuToggle_0_3:import47.MenuToggle;
  _ToolbarItem_0_4:import48.ToolbarItem;
  _query_Button_0_0:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import26.Icon;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_TripDetailsPage1,renderType_TripDetailsPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'menuToggle','');
    this._MenuToggle_0_3 = new import47.MenuToggle(this.parent.parentInjector.get(import49.MenuController),new import31.ElementRef(this._el_0),this.parent.parentInjector.get(import32.ViewController,(null as any)),(<_View_TripDetailsPage0>this.parent)._Navbar_2_4);
    this._ToolbarItem_0_4 = new import48.ToolbarItem(this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import19.Toolbar,(null as any)),(<_View_TripDetailsPage0>this.parent)._Navbar_2_4);
    this._query_Button_0_0 = new import18.QueryList<any>();
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'name','menu');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import26.Icon(this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import26.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import47.MenuToggle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuToggle_0_3; }
    if (((token === import48.ToolbarItem) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ToolbarItem_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._MenuToggle_0_3.menuToggle = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = 'menu';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_2_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_Button_0_0.dirty) {
      this._query_Button_0_0.reset([]);
      this._ToolbarItem_0_4._buttons = this._query_Button_0_0;
      this._query_Button_0_0.notifyOnChanges();
    } }
    const currVal_2:any = this._MenuToggle_0_3.isHidden;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Icon_2_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_0_3.toggle()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_TripDetailsPage1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TripDetailsPage1(viewUtils,parentInjector,declarationEl);
}
class _View_TripDetailsPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ItemSliding_0_4:import50.ItemSliding;
  _query_Item_0_0:import18.QueryList<any>;
  _query_ItemOptions_0_1:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import24.Item;
  _ItemContent_2_5:import24.ItemContent;
  _query_Label_2_0:import18.QueryList<any>;
  _query_Button_2_1:import18.QueryList<any>;
  _query_Icon_2_2:import18.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Avatar_4_3:import51.Avatar;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _ItemOptions_16_3:import50.ItemOptions;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _Button_18_4:import27.Button;
  _text_19:any;
  _el_20:any;
  _Icon_20_3:import26.Icon;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_TripDetailsPage2,renderType_TripDetailsPage,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-sliding',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import52.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import50.ItemSliding((<_View_TripDetailsPage0>this.parent)._List_54_3,this.renderer,new import31.ElementRef(this._el_0),this.parent.parentInjector.get(import39.NgZone));
    this._query_Item_0_0 = new import18.QueryList<any>();
    this._query_ItemOptions_0_1 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this.renderer.setElementAttribute(this._el_2,'ion-item','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import41.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import24.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import24.ItemContent();
    this._query_Label_2_0 = new import18.QueryList<any>();
    this._query_Button_2_1 = new import18.QueryList<any>();
    this._query_Icon_2_2 = new import18.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Avatar_4_3 = new import51.Avatar();
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this.renderer.setElementAttribute(this._el_6,'src','img/avatar.png');
    this.renderer.setElementAttribute(this._el_6,'style','object-fit:cover;width:100%;');
    this._text_7 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [].concat([this._el_4]),
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11,
        this._el_12,
        this._text_14
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this.renderer.setElementAttribute(this._el_16,'side','right');
    this._ItemOptions_16_3 = new import50.ItemOptions(new import31.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'color','primary');
    this.renderer.setElementAttribute(this._el_18,'ion-button','');
    this._appEl_18 = new import2.AppElement(18,16,this,this._el_18);
    var compView_18:any = import43.viewFactory_Button0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Button_18_4 = new import27.Button((null as any),'',this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_18),this.renderer);
    this._appEl_18.initComponent(this._Button_18_4,[],compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_20,'name','mail');
    this.renderer.setElementAttribute(this._el_20,'role','img');
    this._Icon_20_3 = new import26.Icon(this.parent.parentInjector.get(import30.Config),new import31.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText((null as any),'\n        Mensajes\n      ',(null as any));
      compView_18.create(this._Button_18_4,[[].concat([
        this._text_19,
        this._el_20,
        this._text_21
      ]
    )],(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Item_0_0.reset([this._Item_2_4]);
    this._ItemSliding_0_4.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4,[
      [].concat([this._el_2]),
      [].concat([this._el_16])
    ]
    ,(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import51.Avatar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Avatar_4_3; }
    if (((token === import24.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Item_2_4; }
    if (((token === import24.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemContent_2_5; }
    if (((token === import26.Icon) && (20 === requestNodeIndex))) { return this._Icon_20_3; }
    if (((token === import27.Button) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Button_18_4; }
    if (((token === import50.ItemOptions) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ItemOptions_16_3; }
    if (((token === import50.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ItemSliding_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const currVal_2:any = 'right';
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._ItemOptions_16_3.side = currVal_2;
      this._expr_2 = currVal_2;
    }
    changed = false;
    const currVal_3:any = 'primary';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_18_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_18.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'mail';
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_20_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset([this._ItemOptions_16_3]);
        this._ItemSliding_0_4._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_18_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import5.interpolate(1,'',this.context.$implicit.username,'');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_10,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import5.interpolate(1,'',this.context.$implicit.text,'');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_13,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = this._Icon_20_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_20,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_20_3.ngOnDestroy();
  }
}
function viewFactory_TripDetailsPage2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TripDetailsPage2(viewUtils,parentInjector,declarationEl);
}