/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../providers/logs-service';
import * as import4 from '../../providers/trips-service';
import * as import5 from '../../providers/users-service';
import * as import6 from './home';
import * as import7 from '@angular/core/src/linker/view_utils';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/linker/view_type';
import * as import10 from '@angular/core/src/change_detection/change_detection';
import * as import11 from '@angular/http/src/http';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from 'ionic-angular/navigation/nav-controller';
import * as import14 from 'ionic-angular/navigation/nav-params';
import * as import15 from 'ionic-angular/components/loading/loading';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from 'ionic-angular/components/toolbar/toolbar';
import * as import19 from 'ionic-angular/components/navbar/navbar';
import * as import20 from 'ionic-angular/components/button/button';
import * as import21 from 'ionic-angular/components/menu/menu-toggle';
import * as import22 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from 'ionic-angular/components/icon/icon';
import * as import25 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import26 from 'ionic-angular/components/content/content';
import * as import27 from 'ionic-angular/components/item/item';
import * as import28 from 'ionic-angular/components/avatar/avatar';
import * as import29 from '@angular/common/src/directives/ng_if';
import * as import30 from 'ionic-angular/components/list/list';
import * as import31 from '@angular/common/src/directives/ng_for';
import * as import32 from 'ionic-angular/components/fab/fab';
import * as import33 from 'ionic-angular/config/config';
import * as import34 from '@angular/core/src/linker/element_ref';
import * as import35 from 'ionic-angular/navigation/view-controller';
import * as import36 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import37 from 'ionic-angular/components/app/app';
import * as import38 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import39 from 'ionic-angular/components/menu/menu-controller';
import * as import40 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import41 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import42 from 'ionic-angular/util/keyboard';
import * as import43 from '@angular/core/src/zone/ng_zone';
import * as import44 from 'ionic-angular/components/tabs/tabs';
import * as import45 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import46 from 'ionic-angular/util/form';
import * as import47 from '@angular/core/src/linker/template_ref';
import * as import48 from 'ionic-angular/gestures/gesture-controller';
import * as import49 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import50 from '../../node_modules/ionic-angular/components/fab/fab.ngfactory';
import * as import51 from '@angular/core/src/security';
import * as import52 from 'ionic-angular/components/item/item-sliding';
import * as import53 from 'ionic-angular/components/card/card';
import * as import54 from 'ionic-angular/components/badge/badge';
import * as import55 from 'ionic-angular/components/grid/grid';
import * as import56 from '../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LogsService_0_4:import3.LogsService;
  _TripsService_0_5:import4.TripsService;
  _UsersService_0_6:import5.UsersService;
  _HomePage_0_7:import6.HomePage;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import9.ViewType.HOST,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LogsService_0_4 = new import3.LogsService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._TripsService_0_5 = new import4.TripsService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._UsersService_0_6 = new import5.UsersService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._HomePage_0_7 = new import6.HomePage(this.parentInjector.get(import13.NavController),this.parentInjector.get(import12.AlertController),this._LogsService_0_4,this._TripsService_0_5,this._UsersService_0_6,this.parentInjector.get(import14.NavParams),this.parentInjector.get(import15.LoadingController));
    this._appEl_0.initComponent(this._HomePage_0_7,[],compView_0);
    compView_0.create(this._HomePage_0_7,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LogsService) && (0 === requestNodeIndex))) { return this._LogsService_0_4; }
    if (((token === import4.TripsService) && (0 === requestNodeIndex))) { return this._TripsService_0_5; }
    if (((token === import5.UsersService) && (0 === requestNodeIndex))) { return this._UsersService_0_6; }
    if (((token === import6.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_7; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,[],{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import17.ComponentFactory<import6.HomePage> = new import17.ComponentFactory<import6.HomePage>('ng-component',viewFactory_HomePage_Host0,import6.HomePage);
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import6.HomePage> {
  _el_0:any;
  _Header_0_3:import18.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import19.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import20.Button;
  _MenuToggle_4_5:import21.MenuToggle;
  _ToolbarItem_4_6:import22.ToolbarItem;
  _query_Button_4_0:import23.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import24.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import25.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Content_14_4:import26.Content;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _ItemGroup_21_3:import27.ItemGroup;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Item_23_4:import27.Item;
  _ItemContent_23_5:import27.ItemContent;
  _query_Label_23_0:import23.QueryList<any>;
  _query_Button_23_1:import23.QueryList<any>;
  _query_Icon_23_2:import23.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Avatar_25_3:import28.Avatar;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import29.NgIf;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import29.NgIf;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _List_39_3:import30.List;
  _text_40:any;
  _anchor_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _TemplateRef_41_5:any;
  _NgFor_41_6:import31.NgFor;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import2.AppElement;
  _FabContainer_44_4:import32.FabContainer;
  _query_FabButton_44_0:import23.QueryList<any>;
  _query_FabList_44_1:import23.QueryList<any>;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import2.AppElement;
  _FabButton_46_4:import32.FabButton;
  _el_47:any;
  _Icon_47_3:import24.Icon;
  _text_48:any;
  _el_49:any;
  _FabList_49_3:import32.FabList;
  _query_FabButton_49_0:import23.QueryList<any>;
  _text_50:any;
  _el_51:any;
  /*private*/ _appEl_51:import2.AppElement;
  _FabButton_51_4:import32.FabButton;
  _text_52:any;
  _el_53:any;
  _Icon_53_3:import24.Icon;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import9.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import18.Header(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import35.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import36.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import19.Navbar(this.parentInjector.get(import37.App),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import13.NavController,(null as any)),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import38.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import20.Button('','',this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import21.MenuToggle(this.parentInjector.get(import39.MenuController),new import34.ElementRef(this._el_4),this.parentInjector.get(import35.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import22.ToolbarItem(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import18.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import23.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import24.Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import40.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import25.ToolbarTitle(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import18.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'Me',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[[].concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._el_4]),
      [],
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import2.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import41.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import26.Content(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import37.App),this.parentInjector.get(import42.Keyboard),this.parentInjector.get(import43.NgZone),this.parentInjector.get(import35.ViewController,(null as any)),this.parentInjector.get(import44.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n  \n  ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-item-group',(null as any));
    this._ItemGroup_21_3 = new import27.ItemGroup();
    this._text_22 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this._appEl_23 = new import2.AppElement(23,21,this,this._el_23);
    var compView_23:any = import45.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import27.Item(this.parentInjector.get(import46.Form),this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_23),this.renderer);
    this._ItemContent_23_5 = new import27.ItemContent();
    this._query_Label_23_0 = new import23.QueryList<any>();
    this._query_Button_23_1 = new import23.QueryList<any>();
    this._query_Icon_23_2 = new import23.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_25,'item-left','');
    this._Avatar_25_3 = new import28.Avatar();
    this._text_26 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._appEl_27 = new import2.AppElement(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import47.TemplateRef_(this._appEl_27,viewFactory_HomePage1);
    this._NgIf_27_6 = new import29.NgIf(this._appEl_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._appEl_29 = new import2.AppElement(29,25,this,this._anchor_29);
    this._TemplateRef_29_5 = new import47.TemplateRef_(this._appEl_29,viewFactory_HomePage2);
    this._NgIf_29_6 = new import29.NgIf(this._appEl_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_25,'\n      ',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_23_0.reset([]);
    this._Item_23_4.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4,[
      [].concat([this._el_25]),
      [],
      [].concat([
        this._text_24,
        this._text_31,
        this._el_32,
        this._text_34
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_21,'\n\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_21,'\n  ',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_39_3 = new import30.List(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_39),this.renderer,this.parentInjector.get(import48.GestureController));
    this._text_40 = this.renderer.createText(this._el_39,'\n    ',(null as any));
    this._anchor_41 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._appEl_41 = new import2.AppElement(41,39,this,this._anchor_41);
    this._TemplateRef_41_5 = new import47.TemplateRef_(this._appEl_41,viewFactory_HomePage3);
    this._NgFor_41_6 = new import31.NgFor(this._appEl_41.vcRef,this._TemplateRef_41_5,this.parentInjector.get(import49.IterableDiffers),this.ref);
    this._text_42 = this.renderer.createText(this._el_39,'\n  ',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n\n\n\n\n\n  ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-fab',(null as any));
    this.renderer.setElementAttribute(this._el_44,'bottom','');
    this.renderer.setElementAttribute(this._el_44,'right','');
    this._appEl_44 = new import2.AppElement(44,14,this,this._el_44);
    var compView_44:any = import50.viewFactory_FabContainer0(this.viewUtils,this.injector(44),this._appEl_44);
    this._FabContainer_44_4 = new import32.FabContainer(new import34.ElementRef(this._el_44));
    this._query_FabButton_44_0 = new import23.QueryList<any>();
    this._query_FabList_44_1 = new import23.QueryList<any>();
    this._appEl_44.initComponent(this._FabContainer_44_4,[],compView_44);
    this._text_45 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_46,'color','primary');
    this.renderer.setElementAttribute(this._el_46,'ion-fab','');
    this._appEl_46 = new import2.AppElement(46,44,this,this._el_46);
    var compView_46:any = import50.viewFactory_FabButton0(this.viewUtils,this.injector(46),this._appEl_46);
    this._FabButton_46_4 = new import32.FabButton(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_46),this.renderer);
    this._appEl_46.initComponent(this._FabButton_46_4,[],compView_46);
    this._el_47 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_47,'name','add');
    this.renderer.setElementAttribute(this._el_47,'role','img');
    this._Icon_47_3 = new import24.Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_47),this.renderer);
    compView_46.create(this._FabButton_46_4,[[].concat([this._el_47])],(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_49 = this.renderer.createElement((null as any),'ion-fab-list',(null as any));
    this.renderer.setElementAttribute(this._el_49,'side','left');
    this._FabList_49_3 = new import32.FabList(new import34.ElementRef(this._el_49),this.renderer);
    this._query_FabButton_49_0 = new import23.QueryList<any>();
    this._text_50 = this.renderer.createText(this._el_49,'\n      ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_49,'button',(null as any));
    this.renderer.setElementAttribute(this._el_51,'ion-fab','');
    this._appEl_51 = new import2.AppElement(51,49,this,this._el_51);
    var compView_51:any = import50.viewFactory_FabButton0(this.viewUtils,this.injector(51),this._appEl_51);
    this._FabButton_51_4 = new import32.FabButton(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_51),this.renderer);
    this._appEl_51.initComponent(this._FabButton_51_4,[],compView_51);
    this._text_52 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_53,'name','briefcase');
    this.renderer.setElementAttribute(this._el_53,'role','img');
    this._Icon_53_3 = new import24.Icon(this.parentInjector.get(import33.Config),new import34.ElementRef(this._el_53),this.renderer);
    this._text_54 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_51.create(this._FabButton_51_4,[[].concat([
        this._text_52,
        this._el_53,
        this._text_54
      ]
    )],(null as any));
    this._text_55 = this.renderer.createText(this._el_49,'\n      \n    ',(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_FabButton_44_0.reset([this._FabButton_46_4]);
    this._FabContainer_44_4._mainButton = this._query_FabButton_44_0.first;
      compView_44.create(this._FabContainer_44_4,[[].concat([
        this._text_45,
        this._el_46,
        this._text_48,
        this._el_49,
        this._text_56
      ]
    )],(null as any));
    this._text_57 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4,[
      [].concat([this._el_44]),
      [].concat([
        this._text_15,
        this._text_16,
        this._text_17,
        this._text_18,
        this._text_19,
        this._text_20,
        this._el_21,
        this._text_37,
        this._text_38,
        this._el_39,
        this._text_43,
        this._text_57
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_58 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._expr_0 = import10.UNINITIALIZED;
    this._expr_1 = import10.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
    this._expr_8 = import10.UNINITIALIZED;
    this._expr_9 = import10.UNINITIALIZED;
    this._expr_10 = import10.UNINITIALIZED;
    this._expr_11 = import10.UNINITIALIZED;
    this._expr_12 = import10.UNINITIALIZED;
    this._expr_13 = import10.UNINITIALIZED;
    this._expr_14 = import10.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_51,'click',this.eventHandler(this._handle_click_51_0.bind(this)));
    this._expr_16 = import10.UNINITIALIZED;
    this._expr_17 = import10.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._anchor_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import20.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import21.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import22.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import25.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import19.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4; }
    if (((token === import18.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3; }
    if (((token === import47.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import29.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6; }
    if (((token === import47.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import29.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6; }
    if (((token === import28.Avatar) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Avatar_25_3; }
    if (((token === import27.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_23_4; }
    if (((token === import27.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_23_5; }
    if (((token === import27.ItemGroup) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._ItemGroup_21_3; }
    if (((token === import47.TemplateRef) && (41 === requestNodeIndex))) { return this._TemplateRef_41_5; }
    if (((token === import31.NgFor) && (41 === requestNodeIndex))) { return this._NgFor_41_6; }
    if (((token === import30.List) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._List_39_3; }
    if (((token === import24.Icon) && (47 === requestNodeIndex))) { return this._Icon_47_3; }
    if (((token === import32.FabButton) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._FabButton_46_4; }
    if (((token === import24.Icon) && (53 === requestNodeIndex))) { return this._Icon_53_3; }
    if (((token === import32.FabButton) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._FabButton_51_4; }
    if (((token === import32.FabList) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._FabList_49_3; }
    if (((token === import32.FabContainer) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._FabContainer_44_4; }
    if (((token === import26.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Content_14_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import10.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_14_4.ngOnInit(); }
    const currVal_8:any = ((this.context.user.avatar == '') || (this.context.user.avatar == (null as any)));
    if (import7.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_27_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = ((this.context.user.avatar != '') && (this.context.user.avatar != (null as any)));
    if (import7.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_29_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    changes = (null as any);
    const currVal_11:any = this.context.trips;
    if (import7.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgFor_41_6.ngForOf = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import10.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    if ((changes !== (null as any))) { this._NgFor_41_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_41_6.ngDoCheck(); }
    changed = false;
    const currVal_12:any = 'primary';
    if (import7.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._FabButton_46_4.color = currVal_12;
      changed = true;
      this._expr_12 = currVal_12;
    }
    if (changed) { this._appEl_46.componentView.markAsCheckOnce(); }
    const currVal_13:any = 'add';
    if (import7.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Icon_47_3.name = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_16:any = 'briefcase';
    if (import7.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Icon_53_3.name = currVal_16;
      this._expr_16 = currVal_16;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset([]);
        this._Item_23_4._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset([]);
        this._Item_23_4._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_FabButton_49_0.dirty) {
        this._query_FabButton_49_0.reset([this._FabButton_51_4]);
        this._FabList_49_3._setbuttons = this._query_FabButton_49_0;
        this._query_FabButton_49_0.notifyOnChanges();
      }
      if (this._query_FabList_44_1.dirty) {
        this._query_FabList_44_1.reset([this._FabList_49_3]);
        this._FabContainer_44_4._fabLists = this._query_FabList_44_1;
        this._query_FabList_44_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._FabContainer_44_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4._sbPadding;
    if (import7.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = import7.interpolate(1,'',this.context.user.getAlias(),'');
    if (import7.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_33,currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_14:any = this._Icon_47_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_47,'hide',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_17:any = this._Icon_53_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_53,'hide',currVal_17);
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._Icon_47_3.ngOnDestroy();
    this._Icon_53_3.ngOnDestroy();
    this._FabContainer_44_4.ngOnDestroy();
    this._Content_14_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_51_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addTrip()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<import6.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('/home/nicolas/projects/cloudtripper/cloudtripper-frontend/.tmp/pages/home/home.html',0,import16.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage1 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage1,renderType_HomePage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','img/avatar.png');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_HomePage1(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage1(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage2,renderType_HomePage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','object-fit: cover;');
    this._expr_0 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.user.avatar;
    if (import7.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import51.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage2(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage2(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ItemSliding_0_4:import52.ItemSliding;
  _query_Item_0_0:import23.QueryList<any>;
  _query_ItemOptions_0_1:import23.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import27.Item;
  _ItemContent_2_5:import27.ItemContent;
  _query_Label_2_0:import23.QueryList<any>;
  _query_Button_2_1:import23.QueryList<any>;
  _query_Icon_2_2:import23.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _Card_6_3:import53.Card;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _Badge_17_3:import54.Badge;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _Row_22_3:import55.Row;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _Col_25_3:import55.Col;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _Button_27_4:import20.Button;
  _text_28:any;
  _el_29:any;
  _Icon_29_3:import24.Icon;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _Col_33_3:import55.Col;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _Button_35_4:import20.Button;
  _text_36:any;
  _el_37:any;
  _Icon_37_3:import24.Icon;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _ItemOptions_46_3:import52.ItemOptions;
  _text_47:any;
  _el_48:any;
  /*private*/ _appEl_48:import2.AppElement;
  _Button_48_4:import20.Button;
  _text_49:any;
  _el_50:any;
  _Icon_50_3:import24.Icon;
  _text_51:any;
  _text_52:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage3,renderType_HomePage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-sliding',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','no-padding');
    this.renderer.setElementAttribute(this._el_0,'style','background-color:transparent;background:transparent;');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import56.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import52.ItemSliding((<_View_HomePage0>this.parent)._List_39_3,this.renderer,new import34.ElementRef(this._el_0),this.parent.parentInjector.get(import43.NgZone));
    this._query_Item_0_0 = new import23.QueryList<any>();
    this._query_ItemOptions_0_1 = new import23.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','no-padding item item-block');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import45.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import27.Item(this.parent.parentInjector.get(import46.Form),this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import27.ItemContent();
    this._query_Label_2_0 = new import23.QueryList<any>();
    this._query_Button_2_1 = new import23.QueryList<any>();
    this._query_Icon_2_2 = new import23.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','card-background-page');
    this.renderer.setElementAttribute(this._el_4,'item-content','');
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-card',(null as any));
    this._Card_6_3 = new import53.Card(this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','no-padding');
    this.renderer.setElementAttribute(this._el_8,'outline','');
    this._text_9 = this.renderer.createText(this._el_8,'\n              ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'img',(null as any));
    this._text_11 = this.renderer.createText(this._el_8,'\n              ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','card-title');
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_8,'\n              ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','card-subtitle');
    this._text_16 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-badge',(null as any));
    this._Badge_17_3 = new import54.Badge(this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n              ',(null as any));
    this._text_20 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._text_21 = this.renderer.createText(this._el_6,'\n\n            ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_6,'ion-row',(null as any));
    this._Row_22_3 = new import55.Row();
    this._text_23 = this.renderer.createText(this._el_22,' \n              ',(null as any));
    this._text_24 = this.renderer.createText(this._el_22,'\n              ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this._Col_25_3 = new import55.Col();
    this._text_26 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'button',(null as any));
    this.renderer.setElementAttribute(this._el_27,'clear','');
    this.renderer.setElementAttribute(this._el_27,'icon-left','');
    this.renderer.setElementAttribute(this._el_27,'ion-button','');
    this.renderer.setElementAttribute(this._el_27,'small','');
    this._appEl_27 = new import2.AppElement(27,25,this,this._el_27);
    var compView_27:any = import38.viewFactory_Button0(this.viewUtils,this.injector(27),this._appEl_27);
    this._Button_27_4 = new import20.Button((null as any),'',this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_27),this.renderer);
    this._appEl_27.initComponent(this._Button_27_4,[],compView_27);
    this._text_28 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_29,'name','add');
    this.renderer.setElementAttribute(this._el_29,'role','img');
    this._Icon_29_3 = new import24.Icon(this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_29),this.renderer);
    this._text_30 = this.renderer.createText((null as any),'\n          Registrar\n      ',(null as any));
      compView_27.create(this._Button_27_4,[[].concat([
        this._text_28,
        this._el_29,
        this._text_30
      ]
    )],(null as any));
    this._text_31 = this.renderer.createText(this._el_25,'\n      ',(null as any));
    this._text_32 = this.renderer.createText(this._el_22,'\n              ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this._Col_33_3 = new import55.Col();
    this._text_34 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'button',(null as any));
    this.renderer.setElementAttribute(this._el_35,'clear','');
    this.renderer.setElementAttribute(this._el_35,'icon-left','');
    this.renderer.setElementAttribute(this._el_35,'ion-button','');
    this.renderer.setElementAttribute(this._el_35,'small','');
    this._appEl_35 = new import2.AppElement(35,33,this,this._el_35);
    var compView_35:any = import38.viewFactory_Button0(this.viewUtils,this.injector(35),this._appEl_35);
    this._Button_35_4 = new import20.Button((null as any),'',this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_35),this.renderer);
    this._appEl_35.initComponent(this._Button_35_4,[],compView_35);
    this._text_36 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_37,'name','eye');
    this.renderer.setElementAttribute(this._el_37,'role','img');
    this._Icon_37_3 = new import24.Icon(this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_37),this.renderer);
    this._text_38 = this.renderer.createText((null as any),'\n          Detalles\n      ',(null as any));
      compView_35.create(this._Button_35_4,[[].concat([
        this._text_36,
        this._el_37,
        this._text_38
      ]
    )],(null as any));
    this._text_39 = this.renderer.createText(this._el_33,'\n              ',(null as any));
    this._text_40 = this.renderer.createText(this._el_22,'\n              ',(null as any));
    this._text_41 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._text_42 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._text_43 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [],
      [],
      [].concat([
        this._text_3,
        this._text_44
      ]
      ),
      [].concat([this._el_4]),
      []
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n\n      ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this.renderer.setElementAttribute(this._el_46,'side','right');
    this._ItemOptions_46_3 = new import52.ItemOptions(new import34.ElementRef(this._el_46),this.renderer);
    this._text_47 = this.renderer.createText(this._el_46,'\n        ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'button',(null as any));
    this.renderer.setElementAttribute(this._el_48,'color','danger');
    this.renderer.setElementAttribute(this._el_48,'ion-button','');
    this._appEl_48 = new import2.AppElement(48,46,this,this._el_48);
    var compView_48:any = import38.viewFactory_Button0(this.viewUtils,this.injector(48),this._appEl_48);
    this._Button_48_4 = new import20.Button((null as any),'',this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_48),this.renderer);
    this._appEl_48.initComponent(this._Button_48_4,[],compView_48);
    this._text_49 = this.renderer.createText((null as any),' ',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_50,'name','trash');
    this.renderer.setElementAttribute(this._el_50,'role','img');
    this._Icon_50_3 = new import24.Icon(this.parent.parentInjector.get(import33.Config),new import34.ElementRef(this._el_50),this.renderer);
      compView_48.create(this._Button_48_4,[[].concat([
        this._text_49,
        this._el_50
      ]
    )],(null as any));
    this._text_51 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Item_0_0.reset([this._Item_2_4]);
    this._ItemSliding_0_4.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4,[
      [].concat([this._el_2]),
      [].concat([this._el_46])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    this._expr_5 = import10.UNINITIALIZED;
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
    this._expr_8 = import10.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_0.bind(this)));
    this._expr_10 = import10.UNINITIALIZED;
    this._expr_11 = import10.UNINITIALIZED;
    this._expr_12 = import10.UNINITIALIZED;
    this._expr_13 = import10.UNINITIALIZED;
    this._expr_14 = import10.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_48,'click',this.eventHandler(this._handle_click_48_0.bind(this)));
    this._expr_16 = import10.UNINITIALIZED;
    this._expr_17 = import10.UNINITIALIZED;
    this._expr_18 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import54.Badge) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Badge_17_3; }
    if (((token === import24.Icon) && (29 === requestNodeIndex))) { return this._Icon_29_3; }
    if (((token === import20.Button) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Button_27_4; }
    if (((token === import55.Col) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Col_25_3; }
    if (((token === import24.Icon) && (37 === requestNodeIndex))) { return this._Icon_37_3; }
    if (((token === import20.Button) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Button_35_4; }
    if (((token === import55.Col) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Col_33_3; }
    if (((token === import55.Row) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Row_22_3; }
    if (((token === import53.Card) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Card_6_3; }
    if (((token === import27.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Item_2_4; }
    if (((token === import27.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._ItemContent_2_5; }
    if (((token === import24.Icon) && (50 === requestNodeIndex))) { return this._Icon_50_3; }
    if (((token === import20.Button) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Button_48_4; }
    if (((token === import52.ItemOptions) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._ItemOptions_46_3; }
    if (((token === import52.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._ItemSliding_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_5:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Button_27_4.small = currVal_5;
      changed = true;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Button_27_4.clear = currVal_6;
      changed = true;
      this._expr_6 = currVal_6;
    }
    if (changed) { this._appEl_27.componentView.markAsCheckOnce(); }
    const currVal_7:any = 'add';
    if (import7.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Icon_29_3.name = currVal_7;
      this._expr_7 = currVal_7;
    }
    changed = false;
    const currVal_10:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._Button_35_4.small = currVal_10;
      changed = true;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Button_35_4.clear = currVal_11;
      changed = true;
      this._expr_11 = currVal_11;
    }
    if (changed) { this._appEl_35.componentView.markAsCheckOnce(); }
    const currVal_12:any = 'eye';
    if (import7.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Icon_37_3.name = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_14:any = 'right';
    if (import7.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._ItemOptions_46_3.side = currVal_14;
      this._expr_14 = currVal_14;
    }
    changed = false;
    const currVal_16:any = 'danger';
    if (import7.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Button_48_4.color = currVal_16;
      changed = true;
      this._expr_16 = currVal_16;
    }
    if (changed) { this._appEl_48.componentView.markAsCheckOnce(); }
    const currVal_17:any = 'trash';
    if (import7.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._Icon_50_3.name = currVal_17;
      this._expr_17 = currVal_17;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset([this._ItemOptions_46_3]);
        this._ItemSliding_0_4._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_27_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_35_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_48_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this.context.$implicit.Image;
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_10,'src',this.viewUtils.sanitizer.sanitize(import51.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import7.interpolate(1,'\n                ',this.context.$implicit.Destination,'\n                ');
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_13,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import7.interpolate(1,'Toca para ver ',this.context.$implicit.NumberOfLogs,' registros');
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_18,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._Icon_29_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_29,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_13:any = this._Icon_37_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_37,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_18:any = this._Icon_50_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_50,'hide',currVal_18);
      this._expr_18 = currVal_18;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_29_3.ngOnDestroy();
    this._Icon_37_3.ngOnDestroy();
    this._Icon_50_3.ngOnDestroy();
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.loadLogs(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.addLog(this.context.$implicit.Id)) !== false);
    return (true && pd_0);
  }
  private _handle_click_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.showTripDetails(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_48_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.deleteTrip(this.context.$implicit.Id)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage3(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage3(viewUtils,parentInjector,declarationEl);
}