/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../providers/trips-subscriptions-service';
import * as import4 from './app.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from 'ionic-angular/platform/platform';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from 'ionic-angular/components/menu/menu';
import * as import16 from 'ionic-angular/components/toolbar/toolbar';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import18 from 'ionic-angular/components/content/content';
import * as import19 from '@angular/common/src/directives/ng_if';
import * as import20 from 'ionic-angular/components/item/item';
import * as import21 from '@angular/common/src/directives/ng_for';
import * as import22 from 'ionic-angular/components/menu/menu-close';
import * as import23 from 'ionic-angular/components/icon/icon';
import * as import24 from 'ionic-angular/components/nav/nav';
import * as import25 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import26 from 'ionic-angular/components/menu/menu-controller';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/gestures/gesture-controller';
import * as import32 from 'ionic-angular/navigation/view-controller';
import * as import33 from '../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import34 from '../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import35 from 'ionic-angular/components/navbar/navbar';
import * as import36 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import37 from 'ionic-angular/components/app/app';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from '@angular/core/src/linker/template_ref';
import * as import40 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import41 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import42 from 'ionic-angular/util/form';
import * as import43 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import44 from 'ionic-angular/navigation/nav-controller-base';
import * as import45 from '@angular/core/src/linker/component_factory_resolver';
import * as import46 from 'ionic-angular/transitions/transition-controller';
import * as import47 from 'ionic-angular/navigation/deep-linker';
import * as import48 from 'ionic-angular/components/avatar/avatar';
import * as import49 from '@angular/core/src/security';
import * as import50 from 'ionic-angular/components/badge/badge';
var renderType_MyApp_Host:import0.RenderComponentType = (null as any);
class _View_MyApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TripsSubscriptionsService_0_4:import3.TripsSubscriptionsService;
  _MyApp_0_5:import4.MyApp;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp_Host0,renderType_MyApp_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TripsSubscriptionsService_0_4 = new import3.TripsSubscriptionsService(this.parentInjector.get(import9.Http),this.parentInjector.get(import10.AlertController));
    this._MyApp_0_5 = new import4.MyApp(this.parentInjector.get(import11.Platform),this._TripsSubscriptionsService_0_4);
    this._appEl_0.initComponent(this._MyApp_0_5,[],compView_0);
    compView_0.create(this._MyApp_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TripsSubscriptionsService) && (0 === requestNodeIndex))) { return this._TripsSubscriptionsService_0_4; }
    if (((token === import4.MyApp) && (0 === requestNodeIndex))) { return this._MyApp_0_5; }
    return notFoundResult;
  }
}
function viewFactory_MyApp_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MyApp_Host === (null as any))) { (renderType_MyApp_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_MyApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyAppNgFactory:import13.ComponentFactory<import4.MyApp> = new import13.ComponentFactory<import4.MyApp>('ng-component',viewFactory_MyApp_Host0,import4.MyApp);
const styles_MyApp:any[] = [];
var renderType_MyApp:import0.RenderComponentType = (null as any);
class _View_MyApp0 extends import1.AppView<import4.MyApp> {
  _viewQuery_Nav_0:import14.QueryList<any>;
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Menu_0_4:import15.Menu;
  _query_Content_0_0:import14.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Header_2_3:import16.Header;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Toolbar_4_4:import16.Toolbar;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _ToolbarTitle_8_4:import17.ToolbarTitle;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Content_14_4:import18.Content;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import19.NgIf;
  _text_17:any;
  _el_18:any;
  _ItemGroup_18_3:import20.ItemGroup;
  _text_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgFor_21_6:import21.NgFor;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Item_23_4:import20.Item;
  _ItemContent_23_5:import20.ItemContent;
  _MenuClose_23_6:import22.MenuClose;
  _query_Label_23_0:import14.QueryList<any>;
  _query_Button_23_1:import14.QueryList<any>;
  _query_Icon_23_2:import14.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Icon_25_3:import23.Icon;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _Nav_32_4:import24.Nav;
  _text_33:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp0,renderType_MyApp,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import14.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','navigation');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import25.viewFactory_Menu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Menu_0_4 = new import15.Menu(this.parentInjector.get(import26.MenuController),new import27.ElementRef(this._el_0),this.parentInjector.get(import28.Config),this.parentInjector.get(import11.Platform),this.renderer,this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import31.GestureController));
    this._query_Content_0_0 = new import14.QueryList<any>();
    this._appEl_0.initComponent(this._Menu_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_2_3 = new import16.Header(this.parentInjector.get(import28.Config),new import27.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import32.ViewController,(null as any)));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','login-content toolbar');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import33.viewFactory_Toolbar0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Toolbar_4_4 = new import16.Toolbar(this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import28.Config),new import27.ElementRef(this._el_4),this.renderer);
    this._appEl_4.initComponent(this._Toolbar_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_6,'height','40px');
    this.renderer.setElementAttribute(this._el_6,'src','img/icon.png');
    this.renderer.setElementAttribute(this._el_6,'style','margin-left:10px;display:inline-block');
    this.renderer.setElementAttribute(this._el_6,'width','40px');
    this._text_7 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','titleicon');
    this.renderer.setElementAttribute(this._el_8,'style','display:inline-block');
    this._appEl_8 = new import2.AppElement(8,4,this,this._el_8);
    var compView_8:any = import34.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(8),this._appEl_8);
    this._ToolbarTitle_8_4 = new import17.ToolbarTitle(this.parentInjector.get(import28.Config),new import27.ElementRef(this._el_8),this.renderer,this._Toolbar_4_4,this.parentInjector.get(import35.Navbar,(null as any)));
    this._appEl_8.initComponent(this._ToolbarTitle_8_4,[],compView_8);
    this._text_9 = this.renderer.createText((null as any),'Cloudtripper',(null as any));
    compView_8.create(this._ToolbarTitle_8_4,[[].concat([this._text_9])],(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_4.create(this._Toolbar_4_4,[
      [],
      [],
      [],
      [].concat([
        this._text_5,
        this._el_6,
        this._text_7,
        this._el_8,
        this._text_10,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n\n  ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','login-content');
    this._appEl_14 = new import2.AppElement(14,0,this,this._el_14);
    var compView_14:any = import36.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import18.Content(this.parentInjector.get(import28.Config),new import27.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import37.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import38.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_16 = new import2.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import39.TemplateRef_(this._appEl_16,viewFactory_MyApp1);
    this._NgIf_16_6 = new import19.NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-item-group',(null as any));
    this._ItemGroup_18_3 = new import20.ItemGroup();
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._text_20 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_18,(null as any));
    this._appEl_21 = new import2.AppElement(21,18,this,this._anchor_21);
    this._TemplateRef_21_5 = new import39.TemplateRef_(this._appEl_21,viewFactory_MyApp4);
    this._NgFor_21_6 = new import21.NgFor(this._appEl_21.vcRef,this._TemplateRef_21_5,this.parentInjector.get(import40.IterableDiffers),this.ref);
    this._text_22 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this.renderer.setElementAttribute(this._el_23,'color','danger');
    this.renderer.setElementAttribute(this._el_23,'ion-item','');
    this.renderer.setElementAttribute(this._el_23,'menuClose','');
    this.renderer.setElementAttribute(this._el_23,'style','opacity:0.8;');
    this._appEl_23 = new import2.AppElement(23,18,this,this._el_23);
    var compView_23:any = import41.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import20.Item(this.parentInjector.get(import42.Form),this.parentInjector.get(import28.Config),new import27.ElementRef(this._el_23),this.renderer);
    this._ItemContent_23_5 = new import20.ItemContent();
    this._MenuClose_23_6 = new import22.MenuClose(this.parentInjector.get(import26.MenuController));
    this._query_Label_23_0 = new import14.QueryList<any>();
    this._query_Button_23_1 = new import14.QueryList<any>();
    this._query_Icon_23_2 = new import14.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_25,'name','power');
    this.renderer.setElementAttribute(this._el_25,'role','img');
    this._Icon_25_3 = new import23.Icon(this.parentInjector.get(import28.Config),new import27.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText((null as any),' Cerrar sesión\n        ',(null as any));
    this._query_Label_23_0.reset([]);
    this._Item_23_4.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4,[
      [],
      [],
      [].concat([
        this._text_24,
        this._el_25,
        this._text_26
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n    \n  ',(null as any));
    compView_14.create(this._Content_14_4,[
      [],
      [].concat([
        this._text_15,
        this._appEl_16,
        this._text_17,
        this._el_18,
        this._text_28
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_0_0.reset([this._Content_14_4]);
    this._Menu_0_4.menuContent = this._query_Content_0_0.first;
      compView_0.create(this._Menu_0_4,[[].concat([
        this._text_1,
        this._el_2,
        this._text_13,
        this._el_14,
        this._text_29
      ]
    )],(null as any));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_32 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_32,'swipeBackEnabled','false');
    this._appEl_32 = new import2.AppElement(32,(null as any),this,this._el_32);
    var compView_32:any = import43.viewFactory_Nav0(this.viewUtils,this.injector(32),this._appEl_32);
    this._Nav_32_4 = new import24.Nav(this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import44.NavControllerBase,(null as any)),this.parentInjector.get(import37.App),this.parentInjector.get(import28.Config),this.parentInjector.get(import29.Keyboard),new import27.ElementRef(this._el_32),this.parentInjector.get(import30.NgZone),this.renderer,this.parentInjector.get(import45.ComponentFactoryResolver),this.parentInjector.get(import31.GestureController),this.parentInjector.get(import46.TransitionController),this.parentInjector.get(import47.DeepLinker,(null as any)));
    this._appEl_32.initComponent(this._Nav_32_4,[],compView_32);
    compView_32.create(this._Nav_32_4,[],(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_32_4]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.ToolbarTitle) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ToolbarTitle_8_4; }
    if (((token === import16.Toolbar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Toolbar_4_4; }
    if (((token === import16.Header) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_2_3; }
    if (((token === import39.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import19.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6; }
    if (((token === import39.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import21.NgFor) && (21 === requestNodeIndex))) { return this._NgFor_21_6; }
    if (((token === import23.Icon) && (25 === requestNodeIndex))) { return this._Icon_25_3; }
    if (((token === import20.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_23_4; }
    if (((token === import20.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_23_5; }
    if (((token === import22.MenuClose) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._MenuClose_23_6; }
    if (((token === import20.ItemGroup) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ItemGroup_18_3; }
    if (((token === import18.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Content_14_4; }
    if (((token === import15.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Menu_0_4; }
    if (((token === import24.Nav) && (32 === requestNodeIndex))) { return this._Nav_32_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    changed = false;
    const currVal_0:any = this._Nav_32_4;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Menu_0_4.content = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Menu_0_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_14_4.ngOnInit(); }
    const currVal_3:any = (this.context.usersService.currentUser != (null as any));
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_16_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    changes = (null as any);
    const currVal_4:any = this.context.pages;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_21_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_21_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_21_6.ngDoCheck(); }
    changed = false;
    const currVal_7:any = 'danger';
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Item_23_4.color = currVal_7;
      changed = true;
      this._expr_7 = currVal_7;
    }
    if (changed) { this._appEl_23.componentView.markAsCheckOnce(); }
    const currVal_8:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._MenuClose_23_6.menuClose = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = 'power';
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Icon_25_3.name = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_11:any = this.context.rootPage;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Nav_32_4.root = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = 'false';
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Nav_32_4.swipeBackEnabled = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset([]);
        this._Item_23_4._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset([this._Icon_25_3]);
        this._Item_23_4._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Toolbar_4_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_4,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_14_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_10:any = this._Icon_25_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_25,'hide',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_32_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_25_3.ngOnDestroy();
    this._Content_14_4.ngOnDestroy();
    this._Menu_0_4.ngOnDestroy();
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.signOut()) !== false);
    const pd_1:any = ((<any>this._MenuClose_23_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
export function viewFactory_MyApp0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.MyApp> {
  if ((renderType_MyApp === (null as any))) { (renderType_MyApp = viewUtils.createRenderComponentType('/home/nicolas/projects/cloudtripper/cloudtripper-frontend/.tmp/app/app.html',0,import12.ViewEncapsulation.None,styles_MyApp,{})); }
  return new _View_MyApp0(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp1 extends import1.AppView<any> {
  _el_0:any;
  _ItemGroup_0_3:import20.ItemGroup;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import20.Item;
  _ItemContent_2_5:import20.ItemContent;
  _query_Label_2_0:import14.QueryList<any>;
  _query_Button_2_1:import14.QueryList<any>;
  _query_Icon_2_2:import14.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Avatar_4_3:import48.Avatar;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import19.NgIf;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import19.NgIf;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp1,renderType_MyApp,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-group',(null as any));
    this._ItemGroup_0_3 = new import20.ItemGroup();
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import41.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import20.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import28.Config),new import27.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import20.ItemContent();
    this._query_Label_2_0 = new import14.QueryList<any>();
    this._query_Button_2_1 = new import14.QueryList<any>();
    this._query_Icon_2_2 = new import14.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Avatar_4_3 = new import48.Avatar();
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import39.TemplateRef_(this._appEl_6,viewFactory_MyApp2);
    this._NgIf_6_6 = new import19.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._appEl_8 = new import2.AppElement(8,4,this,this._anchor_8);
    this._TemplateRef_8_5 = new import39.TemplateRef_(this._appEl_8,viewFactory_MyApp3);
    this._NgIf_8_6 = new import19.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [].concat([this._el_4]),
      [],
      [].concat([
        this._text_3,
        this._text_10,
        this._el_11,
        this._text_12,
        this._el_13,
        this._text_14
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n      \n      ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import19.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    if (((token === import39.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import19.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    if (((token === import48.Avatar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Avatar_4_3; }
    if (((token === import20.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Item_2_4; }
    if (((token === import20.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemContent_2_5; }
    if (((token === import20.ItemGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ItemGroup_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = ((this.parent.context.usersService.currentUser.avatar == '') || (this.parent.context.usersService.currentUser.avatar == (null as any)));
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_6_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = ((this.parent.context.usersService.currentUser.avatar != '') && (this.parent.context.usersService.currentUser.avatar != (null as any)));
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_8_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this.parent.context.usersService.currentUser.getAlias();
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_11,'innerHTML',this.viewUtils.sanitizer.sanitize(import49.SecurityContext.HTML,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.parent.context.usersService.currentUser.text;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_13,'innerHTML',this.viewUtils.sanitizer.sanitize(import49.SecurityContext.HTML,currVal_3));
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyApp1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyApp1(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp2 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp2,renderType_MyApp,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','img/avatar.png');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_MyApp2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyApp2(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp3,renderType_MyApp,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','object-fit: cover;');
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.parent.context.usersService.currentUser.avatar;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import49.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyApp3(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyApp3(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import20.Item;
  _ItemContent_0_5:import20.ItemContent;
  _MenuClose_0_6:import22.MenuClose;
  _query_Label_0_0:import14.QueryList<any>;
  _query_Button_0_1:import14.QueryList<any>;
  _query_Icon_0_2:import14.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import23.Icon;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import19.NgIf;
  _text_5:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp4,renderType_MyApp,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'color','light');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this.renderer.setElementAttribute(this._el_0,'style','opacity:0.8;');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import20.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import28.Config),new import27.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import20.ItemContent();
    this._MenuClose_0_6 = new import22.MenuClose(this.parent.parentInjector.get(import26.MenuController));
    this._query_Label_0_0 = new import14.QueryList<any>();
    this._query_Button_0_1 = new import14.QueryList<any>();
    this._query_Icon_0_2 = new import14.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import23.Icon(this.parent.parentInjector.get(import28.Config),new import27.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import39.TemplateRef_(this._appEl_4,viewFactory_MyApp5);
    this._NgIf_4_6 = new import19.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_3,
        this._text_5
      ]
      ),
      [],
      [].concat([this._appEl_4])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import39.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import19.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import20.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Item_0_4; }
    if (((token === import20.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ItemContent_0_5; }
    if (((token === import22.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_2:any = 'light';
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Item_0_4.color = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuClose_0_6.menuClose = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import5.interpolate(1,'',this.context.$implicit.icon,'');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_2_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = ((this.context.$implicit.title == 'Novedades') && this.parent.context.tripsSubscriptions.numberOfNews);
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_4_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_5:any = this._Icon_2_3._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import5.interpolate(1,' ',this.context.$implicit.title,'\n        ');
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_3,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MyApp4(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyApp4(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp5 extends import1.AppView<any> {
  _el_0:any;
  _Badge_0_3:import50.Badge;
  _el_1:any;
  _text_2:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp5,renderType_MyApp,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_0,'color','secondary');
    this.renderer.setElementAttribute(this._el_0,'item-right','');
    this._Badge_0_3 = new import50.Badge(this.parent.parent.parentInjector.get(import28.Config),new import27.ElementRef(this._el_0),this.renderer);
    this._el_1 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,' news!',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import50.Badge) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._Badge_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'secondary';
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Badge_0_3.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.parent.parent.context.tripsSubscriptions.numberOfNews;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_1,'innerHTML',this.viewUtils.sanitizer.sanitize(import49.SecurityContext.HTML,currVal_1));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyApp5(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyApp5(viewUtils,parentInjector,declarationEl);
}