/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../providers/users-service';
import * as import4 from './register';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from 'ionic-angular/navigation/nav-controller';
import * as import12 from 'ionic-angular/platform/platform';
import * as import13 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import14 from 'ionic-angular/components/toast/toast';
import * as import15 from 'ionic-angular/components/loading/loading';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from 'ionic-angular/components/toolbar/toolbar';
import * as import19 from 'ionic-angular/components/navbar/navbar';
import * as import20 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import21 from 'ionic-angular/components/content/content';
import * as import22 from 'ionic-angular/components/list/list';
import * as import23 from 'ionic-angular/components/item/item';
import * as import24 from '@angular/core/src/linker/query_list';
import * as import25 from 'ionic-angular/components/label/label';
import * as import26 from '@angular/forms/src/directives/ng_model';
import * as import27 from '@angular/forms/src/directives/ng_control_status';
import * as import28 from 'ionic-angular/components/input/input';
import * as import29 from 'ionic-angular/components/grid/grid';
import * as import30 from 'ionic-angular/components/button/button';
import * as import31 from 'ionic-angular/config/config';
import * as import32 from '@angular/core/src/linker/element_ref';
import * as import33 from 'ionic-angular/navigation/view-controller';
import * as import34 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import35 from 'ionic-angular/components/app/app';
import * as import36 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import37 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import38 from 'ionic-angular/util/keyboard';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from 'ionic-angular/components/tabs/tabs';
import * as import41 from 'ionic-angular/gestures/gesture-controller';
import * as import42 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import43 from 'ionic-angular/util/form';
import * as import44 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import45 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import46 from '@angular/forms/src/directives/ng_control';
import * as import47 from '@angular/core/src/security';
var renderType_RegisterPage_Host:import0.RenderComponentType = (null as any);
class _View_RegisterPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UsersService_0_4:import3.UsersService;
  _RegisterPage_0_5:import4.RegisterPage;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_RegisterPage_Host0,renderType_RegisterPage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RegisterPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UsersService_0_4 = new import3.UsersService(this.parentInjector.get(import9.Http),this.parentInjector.get(import10.AlertController));
    this._RegisterPage_0_5 = new import4.RegisterPage(this.parentInjector.get(import11.NavController),this.parentInjector.get(import12.Platform),this.parentInjector.get(import13.ActionSheetController),this.parentInjector.get(import14.ToastController),this._UsersService_0_4,this.parentInjector.get(import15.LoadingController),this.parentInjector.get(import10.AlertController));
    this._appEl_0.initComponent(this._RegisterPage_0_5,[],compView_0);
    compView_0.create(this._RegisterPage_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UsersService) && (0 === requestNodeIndex))) { return this._UsersService_0_4; }
    if (((token === import4.RegisterPage) && (0 === requestNodeIndex))) { return this._RegisterPage_0_5; }
    return notFoundResult;
  }
}
function viewFactory_RegisterPage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_RegisterPage_Host === (null as any))) { (renderType_RegisterPage_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,[],{})); }
  return new _View_RegisterPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const RegisterPageNgFactory:import17.ComponentFactory<import4.RegisterPage> = new import17.ComponentFactory<import4.RegisterPage>('ng-component',viewFactory_RegisterPage_Host0,import4.RegisterPage);
const styles_RegisterPage:any[] = [];
var renderType_RegisterPage:import0.RenderComponentType = (null as any);
class _View_RegisterPage0 extends import1.AppView<import4.RegisterPage> {
  _el_0:any;
  _Header_0_3:import18.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import19.Navbar;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _ToolbarTitle_5_4:import20.ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _Content_10_4:import21.Content;
  _text_11:any;
  _el_12:any;
  _List_12_3:import22.List;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Item_14_4:import23.Item;
  _ItemContent_14_5:import23.ItemContent;
  _query_Label_14_0:import24.QueryList<any>;
  _query_Button_14_1:import24.QueryList<any>;
  _query_Icon_14_2:import24.QueryList<any>;
  _text_15:any;
  _el_16:any;
  _Label_16_3:import25.Label;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _NgModel_19_4:import26.NgModel;
  _NgControl_19_5:any;
  _NgControlStatus_19_6:import27.NgControlStatus;
  _TextInput_19_7:import28.TextInput;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _Item_22_4:import23.Item;
  _ItemContent_22_5:import23.ItemContent;
  _query_Label_22_0:import24.QueryList<any>;
  _query_Button_22_1:import24.QueryList<any>;
  _query_Icon_22_2:import24.QueryList<any>;
  _text_23:any;
  _el_24:any;
  _Label_24_3:import25.Label;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _NgModel_27_4:import26.NgModel;
  _NgControl_27_5:any;
  _NgControlStatus_27_6:import27.NgControlStatus;
  _TextInput_27_7:import28.TextInput;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _Grid_31_3:import29.Grid;
  _text_32:any;
  _el_33:any;
  _Row_33_3:import29.Row;
  _text_34:any;
  _el_35:any;
  _Col_35_3:import29.Col;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _Col_40_3:import29.Col;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import2.AppElement;
  _Item_42_4:import23.Item;
  _ItemContent_42_5:import23.ItemContent;
  _query_Label_42_0:import24.QueryList<any>;
  _query_Button_42_1:import24.QueryList<any>;
  _query_Icon_42_2:import24.QueryList<any>;
  _text_43:any;
  _el_44:any;
  _Label_44_3:import25.Label;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _NgModel_47_4:import26.NgModel;
  _NgControl_47_5:any;
  _NgControlStatus_47_6:import27.NgControlStatus;
  _TextArea_47_7:import28.TextArea;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _Grid_53_3:import29.Grid;
  _text_54:any;
  _el_55:any;
  _Row_55_3:import29.Row;
  _text_56:any;
  _el_57:any;
  _Col_57_3:import29.Col;
  _text_58:any;
  _el_59:any;
  /*private*/ _appEl_59:import2.AppElement;
  _Button_59_4:import30.Button;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_36:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_RegisterPage0,renderType_RegisterPage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import18.Header(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import33.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import34.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import19.Navbar(this.parentInjector.get(import35.App),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import11.NavController,(null as any)),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import2.AppElement(5,2,this,this._el_5);
    var compView_5:any = import36.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import20.ToolbarTitle(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import18.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'Sign up',(null as any));
    compView_5.create(this._ToolbarTitle_5_4,[[].concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import2.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import37.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import21.Content(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import35.App),this.parentInjector.get(import38.Keyboard),this.parentInjector.get(import39.NgZone),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import40.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4,[],compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_12_3 = new import22.List(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import41.GestureController));
    this._text_13 = this.renderer.createText(this._el_12,'\n    \n  ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','item item-block');
    this.renderer.setElementAttribute(this._el_14,'style','opacity:0.9;');
    this._appEl_14 = new import2.AppElement(14,12,this,this._el_14);
    var compView_14:any = import42.viewFactory_Item0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Item_14_4 = new import23.Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_14),this.renderer);
    this._ItemContent_14_5 = new import23.ItemContent();
    this._query_Label_14_0 = new import24.QueryList<any>();
    this._query_Button_14_1 = new import24.QueryList<any>();
    this._query_Icon_14_2 = new import24.QueryList<any>();
    this._appEl_14.initComponent(this._Item_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_16,'floating','');
    this._Label_16_3 = new import25.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_16),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Usuario',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_19,'name','username');
    this.renderer.setElementAttribute(this._el_19,'type','text');
    this._appEl_19 = new import2.AppElement(19,14,this,this._el_19);
    var compView_19:any = import44.viewFactory_TextInput0(this.viewUtils,this.injector(19),this._appEl_19);
    this._NgModel_19_4 = new import26.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_19_5 = this._NgModel_19_4;
    this._NgControlStatus_19_6 = new import27.NgControlStatus(this._NgControl_19_5);
    this._TextInput_19_7 = new import28.TextInput(this.parentInjector.get(import31.Config),this.parentInjector.get(import43.Form),this._Item_14_4,this.parentInjector.get(import35.App),this.parentInjector.get(import12.Platform),new import32.ElementRef(this._el_19),this.renderer,this._Content_10_4,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_19_5);
    this._appEl_19.initComponent(this._TextInput_19_7,[],compView_19);
    compView_19.create(this._TextInput_19_7,[],(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_14_0.reset([this._Label_16_3]);
    this._Item_14_4.contentLabel = this._query_Label_14_0.first;
    compView_14.create(this._Item_14_4,[
      [],
      [].concat([this._el_16]),
      [].concat([
        this._text_15,
        this._text_18,
        this._text_20
      ]
      ),
      [].concat([this._el_19]),
      []
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_12,'\n\n  ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_12,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','item item-block');
    this.renderer.setElementAttribute(this._el_22,'style','opacity:0.9;');
    this._appEl_22 = new import2.AppElement(22,12,this,this._el_22);
    var compView_22:any = import42.viewFactory_Item0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Item_22_4 = new import23.Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_22),this.renderer);
    this._ItemContent_22_5 = new import23.ItemContent();
    this._query_Label_22_0 = new import24.QueryList<any>();
    this._query_Button_22_1 = new import24.QueryList<any>();
    this._query_Icon_22_2 = new import24.QueryList<any>();
    this._appEl_22.initComponent(this._Item_22_4,[],compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_24,'floating','');
    this._Label_24_3 = new import25.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_24),this.renderer,'',(null as any),(null as any),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Contraseña',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_27,'name','password');
    this.renderer.setElementAttribute(this._el_27,'type','password');
    this._appEl_27 = new import2.AppElement(27,22,this,this._el_27);
    var compView_27:any = import44.viewFactory_TextInput0(this.viewUtils,this.injector(27),this._appEl_27);
    this._NgModel_27_4 = new import26.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_27_5 = this._NgModel_27_4;
    this._NgControlStatus_27_6 = new import27.NgControlStatus(this._NgControl_27_5);
    this._TextInput_27_7 = new import28.TextInput(this.parentInjector.get(import31.Config),this.parentInjector.get(import43.Form),this._Item_22_4,this.parentInjector.get(import35.App),this.parentInjector.get(import12.Platform),new import32.ElementRef(this._el_27),this.renderer,this._Content_10_4,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_27_5);
    this._appEl_27.initComponent(this._TextInput_27_7,[],compView_27);
    compView_27.create(this._TextInput_27_7,[],(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_22_0.reset([this._Label_24_3]);
    this._Item_22_4.contentLabel = this._query_Label_22_0.first;
    compView_22.create(this._Item_22_4,[
      [],
      [].concat([this._el_24]),
      [].concat([
        this._text_23,
        this._text_26,
        this._text_28
      ]
      ),
      [].concat([this._el_27]),
      []
    ]
    ,(null as any));
    this._text_29 = this.renderer.createText(this._el_12,'\n  \n',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_31_3 = new import29.Grid();
    this._text_32 = this.renderer.createText(this._el_31,'\n  ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'ion-row',(null as any));
    this._Row_33_3 = new import29.Row();
    this._text_34 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_35,'width-20','');
    this._Col_35_3 = new import29.Col();
    this._text_36 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'img',(null as any));
    this._text_38 = this.renderer.createText(this._el_35,'            \n    ',(null as any));
    this._text_39 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_33,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_40,'width-80','');
    this._Col_40_3 = new import29.Col();
    this._text_41 = this.renderer.createText(this._el_40,'\n      ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','item item-block');
    this.renderer.setElementAttribute(this._el_42,'style','opacity:0.9;');
    this._appEl_42 = new import2.AppElement(42,40,this,this._el_42);
    var compView_42:any = import42.viewFactory_Item0(this.viewUtils,this.injector(42),this._appEl_42);
    this._Item_42_4 = new import23.Item(this.parentInjector.get(import43.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_42),this.renderer);
    this._ItemContent_42_5 = new import23.ItemContent();
    this._query_Label_42_0 = new import24.QueryList<any>();
    this._query_Button_42_1 = new import24.QueryList<any>();
    this._query_Icon_42_2 = new import24.QueryList<any>();
    this._appEl_42.initComponent(this._Item_42_4,[],compView_42);
    this._text_43 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_44,'stacked','');
    this._Label_44_3 = new import25.Label(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_44),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Contanos sobre vos!',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_47 = this.renderer.createElement((null as any),'ion-textarea',(null as any));
    this.renderer.setElementAttribute(this._el_47,'name','text');
    this.renderer.setElementAttribute(this._el_47,'rows','6');
    this.renderer.setElementAttribute(this._el_47,'type','text');
    this._appEl_47 = new import2.AppElement(47,42,this,this._el_47);
    var compView_47:any = import44.viewFactory_TextArea0(this.viewUtils,this.injector(47),this._appEl_47);
    this._NgModel_47_4 = new import26.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_47_5 = this._NgModel_47_4;
    this._NgControlStatus_47_6 = new import27.NgControlStatus(this._NgControl_47_5);
    this._TextArea_47_7 = new import28.TextArea(this.parentInjector.get(import31.Config),this.parentInjector.get(import43.Form),this._Item_42_4,this.parentInjector.get(import35.App),this.parentInjector.get(import12.Platform),new import32.ElementRef(this._el_47),this.renderer,this._Content_10_4,this.parentInjector.get(import11.NavController,(null as any)),this._NgControl_47_5);
    this._appEl_47.initComponent(this._TextArea_47_7,[],compView_47);
    compView_47.create(this._TextArea_47_7,[],(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_42_0.reset([this._Label_44_3]);
    this._Item_42_4.contentLabel = this._query_Label_42_0.first;
    compView_42.create(this._Item_42_4,[
      [],
      [].concat([this._el_44]),
      [].concat([
        this._text_43,
        this._text_46,
        this._text_48
      ]
      ),
      [].concat([this._el_47]),
      []
    ]
    ,(null as any));
    this._text_49 = this.renderer.createText(this._el_40,'           \n    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_33,'\n  ',(null as any));
    this._text_51 = this.renderer.createText(this._el_31,'\n',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_53_3 = new import29.Grid();
    this._text_54 = this.renderer.createText(this._el_53,'\n  ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'ion-row',(null as any));
    this._Row_55_3 = new import29.Row();
    this._text_56 = this.renderer.createText(this._el_55,'\n    ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'ion-col',(null as any));
    this._Col_57_3 = new import29.Col();
    this._text_58 = this.renderer.createText(this._el_57,'\n      ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_57,'button',(null as any));
    this.renderer.setElementAttribute(this._el_59,'block','');
    this.renderer.setElementAttribute(this._el_59,'ion-button','');
    this._appEl_59 = new import2.AppElement(59,57,this,this._el_59);
    var compView_59:any = import45.viewFactory_Button0(this.viewUtils,this.injector(59),this._appEl_59);
    this._Button_59_4 = new import30.Button((null as any),'',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_59),this.renderer);
    this._appEl_59.initComponent(this._Button_59_4,[],compView_59);
    this._text_60 = this.renderer.createText((null as any),'Comencemos!',(null as any));
    compView_59.create(this._Button_59_4,[[].concat([this._text_60])],(null as any));
    this._text_61 = this.renderer.createText(this._el_57,'\n    ',(null as any));
    this._text_62 = this.renderer.createText(this._el_55,'\n  ',(null as any));
    this._text_63 = this.renderer.createText(this._el_53,'\n',(null as any));
    this._text_64 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_10.create(this._Content_10_4,[
      [],
      [].concat([
        this._text_11,
        this._el_12,
        this._text_30,
        this._el_31,
        this._text_52,
        this._el_53,
        this._text_64
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_65 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_19,'ngModelChange',this.eventHandler(this._handle_ngModelChange_19_0.bind(this)));
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    const subscription_0:any = this._NgModel_19_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_19_0.bind(this)));
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_27,'ngModelChange',this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    const subscription_1:any = this._NgModel_27_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_27_0.bind(this)));
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_24 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_37,'tap',this.eventHandler(this._handle_tap_37_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_47,'ngModelChange',this.eventHandler(this._handle_ngModelChange_47_0.bind(this)));
    this._expr_26 = import8.UNINITIALIZED;
    this._expr_27 = import8.UNINITIALIZED;
    const subscription_2:any = this._NgModel_47_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_47_0.bind(this)));
    this._expr_28 = import8.UNINITIALIZED;
    this._expr_29 = import8.UNINITIALIZED;
    this._expr_30 = import8.UNINITIALIZED;
    this._expr_31 = import8.UNINITIALIZED;
    this._expr_32 = import8.UNINITIALIZED;
    this._expr_33 = import8.UNINITIALIZED;
    this._expr_34 = import8.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_59,'click',this.eventHandler(this._handle_click_59_0.bind(this)));
    this._expr_36 = import8.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4; }
    if (((token === import19.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_2_4; }
    if (((token === import18.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_0_3; }
    if (((token === import25.Label) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Label_16_3; }
    if (((token === import26.NgModel) && (19 === requestNodeIndex))) { return this._NgModel_19_4; }
    if (((token === import46.NgControl) && (19 === requestNodeIndex))) { return this._NgControl_19_5; }
    if (((token === import27.NgControlStatus) && (19 === requestNodeIndex))) { return this._NgControlStatus_19_6; }
    if (((token === import28.TextInput) && (19 === requestNodeIndex))) { return this._TextInput_19_7; }
    if (((token === import23.Item) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Item_14_4; }
    if (((token === import23.ItemContent) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ItemContent_14_5; }
    if (((token === import25.Label) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Label_24_3; }
    if (((token === import26.NgModel) && (27 === requestNodeIndex))) { return this._NgModel_27_4; }
    if (((token === import46.NgControl) && (27 === requestNodeIndex))) { return this._NgControl_27_5; }
    if (((token === import27.NgControlStatus) && (27 === requestNodeIndex))) { return this._NgControlStatus_27_6; }
    if (((token === import28.TextInput) && (27 === requestNodeIndex))) { return this._TextInput_27_7; }
    if (((token === import23.Item) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Item_22_4; }
    if (((token === import23.ItemContent) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ItemContent_22_5; }
    if (((token === import22.List) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._List_12_3; }
    if (((token === import29.Col) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Col_35_3; }
    if (((token === import25.Label) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Label_44_3; }
    if (((token === import26.NgModel) && (47 === requestNodeIndex))) { return this._NgModel_47_4; }
    if (((token === import46.NgControl) && (47 === requestNodeIndex))) { return this._NgControl_47_5; }
    if (((token === import27.NgControlStatus) && (47 === requestNodeIndex))) { return this._NgControlStatus_47_6; }
    if (((token === import28.TextArea) && (47 === requestNodeIndex))) { return this._TextArea_47_7; }
    if (((token === import23.Item) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Item_42_4; }
    if (((token === import23.ItemContent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._ItemContent_42_5; }
    if (((token === import29.Col) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Col_40_3; }
    if (((token === import29.Row) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Row_33_3; }
    if (((token === import29.Grid) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Grid_31_3; }
    if (((token === import30.Button) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Button_59_4; }
    if (((token === import29.Col) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Col_57_3; }
    if (((token === import29.Row) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 62)))) { return this._Row_55_3; }
    if (((token === import29.Grid) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Grid_53_3; }
    if (((token === import21.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Content_10_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_10_4.ngOnInit(); }
    changes = (null as any);
    const currVal_4:any = 'username';
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgModel_19_4.name = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.username;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgModel_19_4.model = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._NgModel_19_4.ngOnChanges(changes); }
    const currVal_12:any = 'text';
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._TextInput_19_7.type = currVal_12;
      this._expr_12 = currVal_12;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_19_7.ngOnInit(); }
    changes = (null as any);
    const currVal_14:any = 'password';
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_27_4.name = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.context.password;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgModel_27_4.model = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._NgModel_27_4.ngOnChanges(changes); }
    const currVal_22:any = 'password';
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._TextInput_27_7.type = currVal_22;
      this._expr_22 = currVal_22;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_27_7.ngOnInit(); }
    changes = (null as any);
    const currVal_26:any = 'text';
    if (import5.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgModel_47_4.name = currVal_26;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import8.SimpleChange(this._expr_26,currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this.context.text;
    if (import5.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgModel_47_4.model = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import8.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    if ((changes !== (null as any))) { this._NgModel_47_4.ngOnChanges(changes); }
    const currVal_34:any = 'text';
    if (import5.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._TextArea_47_7.type = currVal_34;
      this._expr_34 = currVal_34;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextArea_47_7.ngOnInit(); }
    changed = false;
    const currVal_36:any = '';
    if (import5.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._Button_59_4.block = currVal_36;
      changed = true;
      this._expr_36 = currVal_36;
    }
    if (changed) { this._appEl_59.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_14_1.dirty) {
        this._query_Button_14_1.reset([]);
        this._Item_14_4._buttons = this._query_Button_14_1;
        this._query_Button_14_1.notifyOnChanges();
      }
      if (this._query_Icon_14_2.dirty) {
        this._query_Icon_14_2.reset([]);
        this._Item_14_4._icons = this._query_Icon_14_2;
        this._query_Icon_14_2.notifyOnChanges();
      }
      if (this._query_Button_22_1.dirty) {
        this._query_Button_22_1.reset([]);
        this._Item_22_4._buttons = this._query_Button_22_1;
        this._query_Button_22_1.notifyOnChanges();
      }
      if (this._query_Icon_22_2.dirty) {
        this._query_Icon_22_2.reset([]);
        this._Item_22_4._icons = this._query_Icon_22_2;
        this._query_Icon_22_2.notifyOnChanges();
      }
      if (this._query_Button_42_1.dirty) {
        this._query_Button_42_1.reset([]);
        this._Item_42_4._buttons = this._query_Button_42_1;
        this._query_Button_42_1.notifyOnChanges();
      }
      if (this._query_Icon_42_2.dirty) {
        this._query_Icon_42_2.reset([]);
        this._Item_42_4._icons = this._query_Icon_42_2;
        this._query_Icon_42_2.notifyOnChanges();
      }
      this._TextInput_19_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_14_4.ngAfterContentInit(); }
      this._TextInput_27_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_22_4.ngAfterContentInit(); }
      this._TextArea_47_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_42_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_59_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._NgControlStatus_19_6.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_19_6.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_19_6.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_19_6.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_19_6.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_19_6.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_16:any = this._NgControlStatus_27_6.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_27,'ng-untouched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_27_6.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_27,'ng-touched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_27_6.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_27,'ng-pristine',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_27_6.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_27,'ng-dirty',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_27_6.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_27,'ng-valid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_27_6.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_27,'ng-invalid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_24:any = this.context.avatar;
    if (import5.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementProperty(this._el_37,'src',this.viewUtils.sanitizer.sanitize(import47.SecurityContext.URL,currVal_24));
      this._expr_24 = currVal_24;
    }
    const currVal_28:any = this._NgControlStatus_47_6.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_47,'ng-untouched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_47_6.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_47,'ng-touched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_47_6.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_47,'ng-pristine',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_47_6.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_47,'ng-dirty',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_47_6.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_47,'ng-valid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_47_6.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_47,'ng-invalid',currVal_33);
      this._expr_33 = currVal_33;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_19_4.ngOnDestroy();
    this._TextInput_19_7.ngOnDestroy();
    this._NgModel_27_4.ngOnDestroy();
    this._TextInput_27_7.ngOnDestroy();
    this._NgModel_47_4.ngOnDestroy();
    this._TextArea_47_7.ngOnDestroy();
    this._Content_10_4.ngOnDestroy();
  }
  private _handle_ngModelChange_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.username = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_tap_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.presentAddPictureActionSheet()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.text = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_59_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.register()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_RegisterPage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.RegisterPage> {
  if ((renderType_RegisterPage === (null as any))) { (renderType_RegisterPage = viewUtils.createRenderComponentType('/home/nicolas/projects/cloudtripper/cloudtripper-frontend/.tmp/pages/register/register.html',0,import16.ViewEncapsulation.None,styles_RegisterPage,{})); }
  return new _View_RegisterPage0(viewUtils,parentInjector,declarationEl);
}