/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../providers/logs-service';
import * as import4 from '../../providers/trips-service';
import * as import5 from '../../providers/users-service';
import * as import6 from './user';
import * as import7 from '@angular/core/src/linker/view_utils';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/linker/view_type';
import * as import10 from '@angular/core/src/change_detection/change_detection';
import * as import11 from '@angular/http/src/http';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from 'ionic-angular/navigation/nav-controller';
import * as import14 from 'ionic-angular/navigation/nav-params';
import * as import15 from 'ionic-angular/components/loading/loading';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from 'ionic-angular/components/toolbar/toolbar';
import * as import19 from 'ionic-angular/components/navbar/navbar';
import * as import20 from 'ionic-angular/components/button/button';
import * as import21 from 'ionic-angular/components/menu/menu-toggle';
import * as import22 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from 'ionic-angular/components/icon/icon';
import * as import25 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import26 from 'ionic-angular/components/content/content';
import * as import27 from 'ionic-angular/components/item/item';
import * as import28 from 'ionic-angular/components/avatar/avatar';
import * as import29 from 'ionic-angular/components/list/list';
import * as import30 from '@angular/common/src/directives/ng_for';
import * as import31 from 'ionic-angular/config/config';
import * as import32 from '@angular/core/src/linker/element_ref';
import * as import33 from 'ionic-angular/navigation/view-controller';
import * as import34 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import35 from 'ionic-angular/components/app/app';
import * as import36 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import37 from 'ionic-angular/components/menu/menu-controller';
import * as import38 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import39 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import40 from 'ionic-angular/util/keyboard';
import * as import41 from '@angular/core/src/zone/ng_zone';
import * as import42 from 'ionic-angular/components/tabs/tabs';
import * as import43 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import44 from 'ionic-angular/util/form';
import * as import45 from 'ionic-angular/gestures/gesture-controller';
import * as import46 from '@angular/core/src/linker/template_ref';
import * as import47 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import48 from 'ionic-angular/components/card/card';
import * as import49 from 'ionic-angular/components/badge/badge';
import * as import50 from 'ionic-angular/components/grid/grid';
import * as import51 from '@angular/common/src/directives/ng_if';
import * as import52 from '@angular/core/src/security';
var renderType_UserPage_Host:import0.RenderComponentType = (null as any);
class _View_UserPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LogsService_0_4:import3.LogsService;
  _TripsService_0_5:import4.TripsService;
  _UsersService_0_6:import5.UsersService;
  _UserPage_0_7:import6.UserPage;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPage_Host0,renderType_UserPage_Host,import9.ViewType.HOST,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LogsService_0_4 = new import3.LogsService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._TripsService_0_5 = new import4.TripsService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._UsersService_0_6 = new import5.UsersService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._UserPage_0_7 = new import6.UserPage(this.parentInjector.get(import13.NavController),this.parentInjector.get(import12.AlertController),this._LogsService_0_4,this._TripsService_0_5,this._UsersService_0_6,this.parentInjector.get(import14.NavParams),this.parentInjector.get(import15.LoadingController));
    this._appEl_0.initComponent(this._UserPage_0_7,[],compView_0);
    compView_0.create(this._UserPage_0_7,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LogsService) && (0 === requestNodeIndex))) { return this._LogsService_0_4; }
    if (((token === import4.TripsService) && (0 === requestNodeIndex))) { return this._TripsService_0_5; }
    if (((token === import5.UsersService) && (0 === requestNodeIndex))) { return this._UsersService_0_6; }
    if (((token === import6.UserPage) && (0 === requestNodeIndex))) { return this._UserPage_0_7; }
    return notFoundResult;
  }
}
function viewFactory_UserPage_Host0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UserPage_Host === (null as any))) { (renderType_UserPage_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,[],{})); }
  return new _View_UserPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserPageNgFactory:import17.ComponentFactory<import6.UserPage> = new import17.ComponentFactory<import6.UserPage>('ng-component',viewFactory_UserPage_Host0,import6.UserPage);
const styles_UserPage:any[] = [];
var renderType_UserPage:import0.RenderComponentType = (null as any);
class _View_UserPage0 extends import1.AppView<import6.UserPage> {
  _el_0:any;
  _Header_0_3:import18.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import19.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import20.Button;
  _MenuToggle_4_5:import21.MenuToggle;
  _ToolbarItem_4_6:import22.ToolbarItem;
  _query_Button_4_0:import23.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import24.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import25.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _Content_14_4:import26.Content;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _ItemGroup_21_3:import27.ItemGroup;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Item_23_4:import27.Item;
  _ItemContent_23_5:import27.ItemContent;
  _query_Label_23_0:import23.QueryList<any>;
  _query_Button_23_1:import23.QueryList<any>;
  _query_Icon_23_2:import23.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Avatar_25_3:import28.Avatar;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _List_37_3:import29.List;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _TemplateRef_39_5:any;
  _NgFor_39_6:import30.NgFor;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPage0,renderType_UserPage,import9.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import18.Header(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import33.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import34.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import19.Navbar(this.parentInjector.get(import35.App),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import13.NavController,(null as any)),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import36.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import20.Button('','',this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import21.MenuToggle(this.parentInjector.get(import37.MenuController),new import32.ElementRef(this._el_4),this.parentInjector.get(import33.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import22.ToolbarItem(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import18.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import23.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import24.Icon(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import38.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import25.ToolbarTitle(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import18.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'Detalles de usuario',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[[].concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._el_4]),
      [],
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import2.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import39.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import26.Content(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import35.App),this.parentInjector.get(import40.Keyboard),this.parentInjector.get(import41.NgZone),this.parentInjector.get(import33.ViewController,(null as any)),this.parentInjector.get(import42.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4,[],compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n  \n  ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-item-group',(null as any));
    this._ItemGroup_21_3 = new import27.ItemGroup();
    this._text_22 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this._appEl_23 = new import2.AppElement(23,21,this,this._el_23);
    var compView_23:any = import43.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import27.Item(this.parentInjector.get(import44.Form),this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_23),this.renderer);
    this._ItemContent_23_5 = new import27.ItemContent();
    this._query_Label_23_0 = new import23.QueryList<any>();
    this._query_Button_23_1 = new import23.QueryList<any>();
    this._query_Icon_23_2 = new import23.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_25,'item-left','');
    this._Avatar_25_3 = new import28.Avatar();
    this._text_26 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'img',(null as any));
    this.renderer.setElementAttribute(this._el_27,'src','img/avatar.png');
    this._text_28 = this.renderer.createText(this._el_25,'\n      ',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_23_0.reset([]);
    this._Item_23_4.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4,[
      [].concat([this._el_25]),
      [],
      [].concat([
        this._text_24,
        this._text_29,
        this._el_30,
        this._text_32
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(this._el_21,'\n\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_21,'\n  ',(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_37_3 = new import29.List(this.parentInjector.get(import31.Config),new import32.ElementRef(this._el_37),this.renderer,this.parentInjector.get(import45.GestureController));
    this._text_38 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._appEl_39 = new import2.AppElement(39,37,this,this._anchor_39);
    this._TemplateRef_39_5 = new import46.TemplateRef_(this._appEl_39,viewFactory_UserPage1);
    this._NgFor_39_6 = new import30.NgFor(this._appEl_39.vcRef,this._TemplateRef_39_5,this.parentInjector.get(import47.IterableDiffers),this.ref);
    this._text_40 = this.renderer.createText(this._el_37,'\n  ',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4,[
      [],
      [].concat([
        this._text_15,
        this._text_16,
        this._text_17,
        this._text_18,
        this._text_19,
        this._text_20,
        this._el_21,
        this._text_35,
        this._text_36,
        this._el_37,
        this._text_41
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._expr_0 = import10.UNINITIALIZED;
    this._expr_1 = import10.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
    this._expr_8 = import10.UNINITIALIZED;
    this._expr_9 = import10.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._text_41,
      this._text_42
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import20.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import21.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import22.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import25.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import19.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4; }
    if (((token === import18.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3; }
    if (((token === import28.Avatar) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Avatar_25_3; }
    if (((token === import27.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Item_23_4; }
    if (((token === import27.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ItemContent_23_5; }
    if (((token === import27.ItemGroup) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemGroup_21_3; }
    if (((token === import46.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import30.NgFor) && (39 === requestNodeIndex))) { return this._NgFor_39_6; }
    if (((token === import29.List) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._List_37_3; }
    if (((token === import26.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Content_14_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import10.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_14_4.ngOnInit(); }
    changes = (null as any);
    const currVal_9:any = this.context.trips;
    if (import7.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgFor_39_6.ngForOf = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import10.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgFor_39_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_39_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset([]);
        this._Item_23_4._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset([]);
        this._Item_23_4._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4._sbPadding;
    if (import7.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import7.interpolate(1,'',this.context.user.username,'');
    if (import7.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_31,currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._Content_14_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UserPage0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<import6.UserPage> {
  if ((renderType_UserPage === (null as any))) { (renderType_UserPage = viewUtils.createRenderComponentType('/home/nicolas/projects/cloudtripper/cloudtripper-frontend/.tmp/pages/user/user.html',0,import16.ViewEncapsulation.None,styles_UserPage,{})); }
  return new _View_UserPage0(viewUtils,parentInjector,declarationEl);
}
class _View_UserPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import48.Card;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _Badge_13_3:import49.Badge;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _Badge_16_3:import49.Badge;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _Row_22_3:import50.Row;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import51.NgIf;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import51.NgIf;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import51.NgIf;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _TemplateRef_30_5:any;
  _NgIf_30_6:import51.NgIf;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPage1,renderType_UserPage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','card-background-page');
    this.renderer.setElementAttribute(this._el_0,'item-content','');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card',(null as any));
    this._Card_2_3 = new import48.Card(this.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','no-padding');
    this.renderer.setElementAttribute(this._el_4,'outline','');
    this._text_5 = this.renderer.createText(this._el_4,'\n      \n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','card-title');
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','card-subtitle');
    this._text_12 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-badge',(null as any));
    this._Badge_13_3 = new import49.Badge(this.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_11,'ion-badge',(null as any));
    this._Badge_16_3 = new import49.Badge(this.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_19 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n\n      ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_2,'ion-row',(null as any));
    this._Row_22_3 = new import50.Row();
    this._text_23 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_24 = new import2.AppElement(24,22,this,this._anchor_24);
    this._TemplateRef_24_5 = new import46.TemplateRef_(this._appEl_24,viewFactory_UserPage2);
    this._NgIf_24_6 = new import51.NgIf(this._appEl_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_26 = new import2.AppElement(26,22,this,this._anchor_26);
    this._TemplateRef_26_5 = new import46.TemplateRef_(this._appEl_26,viewFactory_UserPage3);
    this._NgIf_26_6 = new import51.NgIf(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_28 = new import2.AppElement(28,22,this,this._anchor_28);
    this._TemplateRef_28_5 = new import46.TemplateRef_(this._appEl_28,viewFactory_UserPage4);
    this._NgIf_28_6 = new import51.NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_30 = new import2.AppElement(30,22,this,this._anchor_30);
    this._TemplateRef_30_5 = new import46.TemplateRef_(this._appEl_30,viewFactory_UserPage5);
    this._NgIf_30_6 = new import51.NgIf(this._appEl_30.vcRef,this._TemplateRef_30_5);
    this._text_31 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._text_32 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
    this._expr_8 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import49.Badge) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Badge_13_3; }
    if (((token === import49.Badge) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Badge_16_3; }
    if (((token === import46.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import51.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6; }
    if (((token === import46.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import51.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6; }
    if (((token === import46.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import51.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6; }
    if (((token === import46.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import51.NgIf) && (30 === requestNodeIndex))) { return this._NgIf_30_6; }
    if (((token === import50.Row) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Row_22_3; }
    if (((token === import48.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Card_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:any = this.context.$implicit.Subscribed;
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_24_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:boolean = !this.context.$implicit.Subscribed;
    if (import7.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_26_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.$implicit.Subscribed;
    if (import7.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_28_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.context.$implicit.Subscribed;
    if (import7.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_30_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.context.$implicit.Image;
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import52.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import7.interpolate(2,'\n          ',this.context.$implicit.UserName,' in ',this.context.$implicit.Destination,'\n        ');
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_9,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import7.interpolate(1,'',this.context.$implicit.NumberOfLogs,' registros');
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_14,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import7.interpolate(1,'',this.context.$implicit.NumberOfSubscriptions,' suscriptores');
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_17,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.showTripLogs(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserPage1(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserPage1(viewUtils,parentInjector,declarationEl);
}
class _View_UserPage2 extends import1.AppView<any> {
  _el_0:any;
  _Col_0_3:import50.Col;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import20.Button;
  _text_3:any;
  _el_4:any;
  _Icon_4_3:import24.Icon;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPage2,renderType_UserPage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this._Col_0_3 = new import50.Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'clear','');
    this.renderer.setElementAttribute(this._el_2,'icon-left','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'small','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import36.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import20.Button((null as any),'',this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_4,'name','image');
    this.renderer.setElementAttribute(this._el_4,'role','img');
    this._Icon_4_3 = new import24.Icon(this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Imágenes',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n          ',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._text_3,
        this._el_4,
        this._text_5,
        this._el_6,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (4 === requestNodeIndex))) { return this._Icon_4_3; }
    if (((token === import20.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_2_4; }
    if (((token === import50.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Col_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.small = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.clear = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_3:any = 'image';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_4_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_4:any = this._Icon_4_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_4,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_4_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.showTripPhotos(this.parent.context.$implicit.Id)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserPage2(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserPage2(viewUtils,parentInjector,declarationEl);
}
class _View_UserPage3 extends import1.AppView<any> {
  _el_0:any;
  _Col_0_3:import50.Col;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import20.Button;
  _text_3:any;
  _el_4:any;
  _Icon_4_3:import24.Icon;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPage3,renderType_UserPage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this._Col_0_3 = new import50.Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','subscribe-button');
    this.renderer.setElementAttribute(this._el_2,'clear','');
    this.renderer.setElementAttribute(this._el_2,'color','secondary');
    this.renderer.setElementAttribute(this._el_2,'icon-left','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'small','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import36.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import20.Button((null as any),'',this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_4,'name','add');
    this.renderer.setElementAttribute(this._el_4,'role','img');
    this._Icon_4_3 = new import24.Icon(this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText((null as any),'\n            Agregar a mis suscripciones\n          ',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._text_3,
        this._el_4,
        this._text_5
      ]
    )],(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (4 === requestNodeIndex))) { return this._Icon_4_3; }
    if (((token === import20.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Button_2_4; }
    if (((token === import50.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Col_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.small = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.clear = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'secondary';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_2_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'add';
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_4_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_5:any = this._Icon_4_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_4,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_4_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.subscribe(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserPage3(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserPage3(viewUtils,parentInjector,declarationEl);
}
class _View_UserPage4 extends import1.AppView<any> {
  _el_0:any;
  _Col_0_3:import50.Col;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import20.Button;
  _text_3:any;
  _el_4:any;
  _Icon_4_3:import24.Icon;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPage4,renderType_UserPage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this._Col_0_3 = new import50.Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'clear','');
    this.renderer.setElementAttribute(this._el_2,'color','danger');
    this.renderer.setElementAttribute(this._el_2,'icon-left','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'small','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import36.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import20.Button((null as any),'',this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_4,'name','close');
    this.renderer.setElementAttribute(this._el_4,'role','img');
    this._Icon_4_3 = new import24.Icon(this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText((null as any),'\n          Desuscribir\n      ',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._text_3,
        this._el_4,
        this._text_5
      ]
    )],(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (4 === requestNodeIndex))) { return this._Icon_4_3; }
    if (((token === import20.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Button_2_4; }
    if (((token === import50.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Col_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.small = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.clear = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'danger';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_2_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'close';
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_4_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_5:any = this._Icon_4_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_4,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_4_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.unsubscribe(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserPage4(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserPage4(viewUtils,parentInjector,declarationEl);
}
class _View_UserPage5 extends import1.AppView<any> {
  _el_0:any;
  _Col_0_3:import50.Col;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import20.Button;
  _text_3:any;
  _el_4:any;
  _Icon_4_3:import24.Icon;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_UserPage5,renderType_UserPage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this._Col_0_3 = new import50.Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'clear','');
    this.renderer.setElementAttribute(this._el_2,'icon-left','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'small','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import36.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import20.Button((null as any),'',this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_4,'name','eye');
    this.renderer.setElementAttribute(this._el_4,'role','img');
    this._Icon_4_3 = new import24.Icon(this.parent.parent.parentInjector.get(import31.Config),new import32.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText((null as any),'\n          Detalles\n      ',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._text_3,
        this._el_4,
        this._text_5
      ]
    )],(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (4 === requestNodeIndex))) { return this._Icon_4_3; }
    if (((token === import20.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Button_2_4; }
    if (((token === import50.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Col_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.small = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.clear = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_3:any = 'eye';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_4_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_4:any = this._Icon_4_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_4,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_4_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.showTripDetails(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserPage5(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserPage5(viewUtils,parentInjector,declarationEl);
}