/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../providers/logs-service';
import * as import4 from '../../providers/trips-subscriptions-service';
import * as import5 from '../../providers/trips-service';
import * as import6 from './trips';
import * as import7 from '@angular/core/src/linker/view_utils';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/linker/view_type';
import * as import10 from '@angular/core/src/change_detection/change_detection';
import * as import11 from '@angular/http/src/http';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from 'ionic-angular/navigation/nav-controller';
import * as import14 from 'ionic-angular/navigation/nav-params';
import * as import15 from 'ionic-angular/components/loading/loading';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from 'ionic-angular/components/toolbar/toolbar';
import * as import19 from 'ionic-angular/components/navbar/navbar';
import * as import20 from 'ionic-angular/components/button/button';
import * as import21 from 'ionic-angular/components/menu/menu-toggle';
import * as import22 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from 'ionic-angular/components/icon/icon';
import * as import25 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import26 from '@angular/forms/src/directives/ng_model';
import * as import27 from '@angular/forms/src/directives/ng_control_status';
import * as import28 from 'ionic-angular/components/segment/segment';
import * as import29 from 'ionic-angular/components/badge/badge';
import * as import30 from 'ionic-angular/components/content/content';
import * as import31 from 'ionic-angular/components/refresher/refresher';
import * as import32 from 'ionic-angular/components/refresher/refresher-content';
import * as import33 from 'ionic-angular/components/list/list';
import * as import34 from '@angular/common/src/directives/ng_for';
import * as import35 from 'ionic-angular/components/infinite-scroll/infinite-scroll';
import * as import36 from 'ionic-angular/components/infinite-scroll/infinite-scroll-content';
import * as import37 from 'ionic-angular/config/config';
import * as import38 from '@angular/core/src/linker/element_ref';
import * as import39 from 'ionic-angular/navigation/view-controller';
import * as import40 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import41 from 'ionic-angular/components/app/app';
import * as import42 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import43 from 'ionic-angular/components/menu/menu-controller';
import * as import44 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import45 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import46 from '../../node_modules/ionic-angular/components/segment/segment.ngfactory';
import * as import47 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import48 from 'ionic-angular/util/keyboard';
import * as import49 from '@angular/core/src/zone/ng_zone';
import * as import50 from 'ionic-angular/components/tabs/tabs';
import * as import51 from 'ionic-angular/gestures/gesture-controller';
import * as import52 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import53 from '@angular/core/src/linker/template_ref';
import * as import54 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import55 from '../../node_modules/ionic-angular/components/infinite-scroll/infinite-scroll-content.ngfactory';
import * as import56 from '@angular/forms/src/directives/ng_control';
import * as import57 from '@angular/core/src/security';
import * as import58 from 'ionic-angular/components/card/card';
import * as import59 from 'ionic-angular/components/grid/grid';
import * as import60 from '@angular/common/src/directives/ng_if';
var renderType_TripsPage_Host:import0.RenderComponentType = (null as any);
class _View_TripsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LogsService_0_4:import3.LogsService;
  _TripsSubscriptionsService_0_5:import4.TripsSubscriptionsService;
  _TripsService_0_6:import5.TripsService;
  _TripsPage_0_7:import6.TripsPage;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_TripsPage_Host0,renderType_TripsPage_Host,import9.ViewType.HOST,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TripsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LogsService_0_4 = new import3.LogsService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._TripsSubscriptionsService_0_5 = new import4.TripsSubscriptionsService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._TripsService_0_6 = new import5.TripsService(this.parentInjector.get(import11.Http),this.parentInjector.get(import12.AlertController));
    this._TripsPage_0_7 = new import6.TripsPage(this.parentInjector.get(import13.NavController),this._LogsService_0_4,this._TripsSubscriptionsService_0_5,this.parentInjector.get(import14.NavParams),this.parentInjector.get(import15.LoadingController),this._TripsService_0_6);
    this._appEl_0.initComponent(this._TripsPage_0_7,[],compView_0);
    compView_0.create(this._TripsPage_0_7,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LogsService) && (0 === requestNodeIndex))) { return this._LogsService_0_4; }
    if (((token === import4.TripsSubscriptionsService) && (0 === requestNodeIndex))) { return this._TripsSubscriptionsService_0_5; }
    if (((token === import5.TripsService) && (0 === requestNodeIndex))) { return this._TripsService_0_6; }
    if (((token === import6.TripsPage) && (0 === requestNodeIndex))) { return this._TripsPage_0_7; }
    return notFoundResult;
  }
}
function viewFactory_TripsPage_Host0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TripsPage_Host === (null as any))) { (renderType_TripsPage_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,[],{})); }
  return new _View_TripsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const TripsPageNgFactory:import17.ComponentFactory<import6.TripsPage> = new import17.ComponentFactory<import6.TripsPage>('ng-component',viewFactory_TripsPage_Host0,import6.TripsPage);
const styles_TripsPage:any[] = [];
var renderType_TripsPage:import0.RenderComponentType = (null as any);
class _View_TripsPage0 extends import1.AppView<import6.TripsPage> {
  _el_0:any;
  _Header_0_3:import18.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import19.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import20.Button;
  _MenuToggle_4_5:import21.MenuToggle;
  _ToolbarItem_4_6:import22.ToolbarItem;
  _query_Button_4_0:import23.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import24.Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ToolbarTitle_9_4:import25.ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _Toolbar_13_4:import18.Toolbar;
  _text_14:any;
  _el_15:any;
  _NgModel_15_3:import26.NgModel;
  _NgControl_15_4:any;
  _NgControlStatus_15_5:import27.NgControlStatus;
  _Segment_15_6:import28.Segment;
  _query_SegmentButton_15_0:import23.QueryList<any>;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _SegmentButton_17_4:import28.SegmentButton;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _Badge_20_3:import29.Badge;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _SegmentButton_23_4:import28.SegmentButton;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _Content_30_4:import30.Content;
  _text_31:any;
  _el_32:any;
  _Refresher_32_3:import31.Refresher;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _RefresherContent_34_4:import32.RefresherContent;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _List_37_3:import33.List;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _appEl_39:import2.AppElement;
  _TemplateRef_39_5:any;
  _NgFor_39_6:import34.NgFor;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _InfiniteScroll_42_3:import35.InfiniteScroll;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import2.AppElement;
  _InfiniteScrollContent_44_4:import36.InfiniteScrollContent;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_29:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_TripsPage0,renderType_TripsPage,import9.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import18.Header(this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import39.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import40.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import19.Navbar(this.parentInjector.get(import41.App),this.parentInjector.get(import39.ViewController,(null as any)),this.parentInjector.get(import13.NavController,(null as any)),this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import42.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import20.Button('','',this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import21.MenuToggle(this.parentInjector.get(import43.MenuController),new import38.ElementRef(this._el_4),this.parentInjector.get(import39.ViewController,(null as any)),this._Navbar_2_4);
    this._ToolbarItem_4_6 = new import22.ToolbarItem(this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import18.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_4_0 = new import23.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import24.Icon(this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import2.AppElement(9,2,this,this._el_9);
    var compView_9:any = import44.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import25.ToolbarTitle(this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import18.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'Viajes',(null as any));
    compView_9.create(this._ToolbarTitle_9_4,[[].concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [].concat([this._el_4]),
      [],
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','toolbar');
    this._appEl_13 = new import2.AppElement(13,0,this,this._el_13);
    var compView_13:any = import45.viewFactory_Toolbar0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Toolbar_13_4 = new import18.Toolbar(this.parentInjector.get(import39.ViewController,(null as any)),this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_13),this.renderer);
    this._appEl_13.initComponent(this._Toolbar_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-segment',(null as any));
    this._NgModel_15_3 = new import26.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_15_4 = this._NgModel_15_3;
    this._NgControlStatus_15_5 = new import27.NgControlStatus(this._NgControl_15_4);
    this._Segment_15_6 = new import28.Segment(this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_15),this.renderer,this._NgControl_15_4);
    this._query_SegmentButton_15_0 = new import23.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','segment-button');
    this.renderer.setElementAttribute(this._el_17,'role','button');
    this.renderer.setElementAttribute(this._el_17,'tappable','');
    this.renderer.setElementAttribute(this._el_17,'value','subscriptions');
    this._appEl_17 = new import2.AppElement(17,15,this,this._el_17);
    var compView_17:any = import46.viewFactory_SegmentButton0(this.viewUtils,this.injector(17),this._appEl_17);
    this._SegmentButton_17_4 = new import28.SegmentButton(this.renderer,new import38.ElementRef(this._el_17));
    this._appEl_17.initComponent(this._SegmentButton_17_4,[],compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n        Mis suscripciones ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this._Badge_20_3 = new import29.Badge(this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText((null as any),' \n      ',(null as any));
      compView_17.create(this._SegmentButton_17_4,[[].concat([
        this._text_18,
        this._text_19,
        this._el_20,
        this._text_21
      ]
    )],(null as any));
    this._text_22 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_15,'ion-segment-button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','segment-button');
    this.renderer.setElementAttribute(this._el_23,'role','button');
    this.renderer.setElementAttribute(this._el_23,'tappable','');
    this.renderer.setElementAttribute(this._el_23,'value','all');
    this._appEl_23 = new import2.AppElement(23,15,this,this._el_23);
    var compView_23:any = import46.viewFactory_SegmentButton0(this.viewUtils,this.injector(23),this._appEl_23);
    this._SegmentButton_23_4 = new import28.SegmentButton(this.renderer,new import38.ElementRef(this._el_23));
    this._appEl_23.initComponent(this._SegmentButton_23_4,[],compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n        Todos\n      ',(null as any));
      compView_23.create(this._SegmentButton_23_4,[[].concat([
        this._text_24,
        this._text_25
      ]
    )],(null as any));
    this._text_26 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_13.create(this._Toolbar_13_4,[
      [],
      [],
      [],
      [].concat([
        this._text_14,
        this._el_15,
        this._text_27
      ]
      )
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_30 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_30 = new import2.AppElement(30,(null as any),this,this._el_30);
    var compView_30:any = import47.viewFactory_Content0(this.viewUtils,this.injector(30),this._appEl_30);
    this._Content_30_4 = new import30.Content(this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_30),this.renderer,this.parentInjector.get(import41.App),this.parentInjector.get(import48.Keyboard),this.parentInjector.get(import49.NgZone),this.parentInjector.get(import39.ViewController,(null as any)),this.parentInjector.get(import50.Tabs,(null as any)));
    this._appEl_30.initComponent(this._Content_30_4,[],compView_30);
    this._text_31 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'ion-refresher',(null as any));
    this._Refresher_32_3 = new import31.Refresher(this._Content_30_4,this.parentInjector.get(import49.NgZone),this.parentInjector.get(import51.GestureController));
    this._text_33 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'ion-refresher-content',(null as any));
    this._appEl_34 = new import2.AppElement(34,32,this,this._el_34);
    var compView_34:any = import52.viewFactory_RefresherContent0(this.viewUtils,this.injector(34),this._appEl_34);
    this._RefresherContent_34_4 = new import32.RefresherContent(this._Refresher_32_3,this.parentInjector.get(import37.Config));
    this._appEl_34.initComponent(this._RefresherContent_34_4,[],compView_34);
    compView_34.create(this._RefresherContent_34_4,[],(null as any));
    this._text_35 = this.renderer.createText(this._el_32,'\n  ',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_37_3 = new import33.List(this.parentInjector.get(import37.Config),new import38.ElementRef(this._el_37),this.renderer,this.parentInjector.get(import51.GestureController));
    this._text_38 = this.renderer.createText(this._el_37,'\n    ',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor(this._el_37,(null as any));
    this._appEl_39 = new import2.AppElement(39,37,this,this._anchor_39);
    this._TemplateRef_39_5 = new import53.TemplateRef_(this._appEl_39,viewFactory_TripsPage1);
    this._NgFor_39_6 = new import34.NgFor(this._appEl_39.vcRef,this._TemplateRef_39_5,this.parentInjector.get(import54.IterableDiffers),this.ref);
    this._text_40 = this.renderer.createText(this._el_37,'\n  ',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n  \n  ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'ion-infinite-scroll',(null as any));
    this._InfiniteScroll_42_3 = new import35.InfiniteScroll(this._Content_30_4,this.parentInjector.get(import49.NgZone),new import38.ElementRef(this._el_42));
    this._text_43 = this.renderer.createText(this._el_42,'\n    ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'ion-infinite-scroll-content',(null as any));
    this._appEl_44 = new import2.AppElement(44,42,this,this._el_44);
    var compView_44:any = import55.viewFactory_InfiniteScrollContent0(this.viewUtils,this.injector(44),this._appEl_44);
    this._InfiniteScrollContent_44_4 = new import36.InfiniteScrollContent(this._InfiniteScroll_42_3,this.parentInjector.get(import37.Config));
    this._appEl_44.initComponent(this._InfiniteScrollContent_44_4,[],compView_44);
    compView_44.create(this._InfiniteScrollContent_44_4,[],(null as any));
    this._text_45 = this.renderer.createText(this._el_42,'\n  ',(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n',(null as any));
    compView_30.create(this._Content_30_4,[
      [],
      [].concat([
        this._text_31,
        this._text_36,
        this._el_37,
        this._text_41,
        this._el_42,
        this._text_46
      ]
      ),
      [].concat([this._el_32])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import10.UNINITIALIZED;
    this._expr_1 = import10.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_15,'ngModelChange',this.eventHandler(this._handle_ngModelChange_15_0.bind(this)));
    this._expr_9 = import10.UNINITIALIZED;
    const subscription_0:any = this._NgModel_15_3.update.subscribe(this.eventHandler(this._handle_ngModelChange_15_0.bind(this)));
    this._expr_10 = import10.UNINITIALIZED;
    this._expr_11 = import10.UNINITIALIZED;
    this._expr_12 = import10.UNINITIALIZED;
    this._expr_13 = import10.UNINITIALIZED;
    this._expr_14 = import10.UNINITIALIZED;
    this._expr_15 = import10.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this._expr_18 = import10.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_21 = import10.UNINITIALIZED;
    this._expr_22 = import10.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_32,'ionRefresh',this.eventHandler(this._handle_ionRefresh_32_0.bind(this)));
    this._expr_24 = import10.UNINITIALIZED;
    this._expr_25 = import10.UNINITIALIZED;
    const subscription_1:any = this._Refresher_32_3.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_32_0.bind(this)));
    this._expr_26 = import10.UNINITIALIZED;
    this._expr_27 = import10.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_42,'ionInfinite',this.eventHandler(this._handle_ionInfinite_42_0.bind(this)));
    const subscription_2:any = this._InfiniteScroll_42_3.ionInfinite.subscribe(this.eventHandler(this._handle_ionInfinite_42_0.bind(this)));
    this._expr_29 = import10.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3; }
    if (((token === import20.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4; }
    if (((token === import21.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5; }
    if (((token === import22.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6; }
    if (((token === import25.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4; }
    if (((token === import19.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4; }
    if (((token === import29.Badge) && (20 === requestNodeIndex))) { return this._Badge_20_3; }
    if (((token === import28.SegmentButton) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._SegmentButton_17_4; }
    if (((token === import28.SegmentButton) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._SegmentButton_23_4; }
    if (((token === import26.NgModel) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgModel_15_3; }
    if (((token === import56.NgControl) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgControl_15_4; }
    if (((token === import27.NgControlStatus) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgControlStatus_15_5; }
    if (((token === import28.Segment) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Segment_15_6; }
    if (((token === import18.Toolbar) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Toolbar_13_4; }
    if (((token === import18.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Header_0_3; }
    if (((token === import32.RefresherContent) && (34 === requestNodeIndex))) { return this._RefresherContent_34_4; }
    if (((token === import31.Refresher) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Refresher_32_3; }
    if (((token === import53.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import34.NgFor) && (39 === requestNodeIndex))) { return this._NgFor_39_6; }
    if (((token === import33.List) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._List_37_3; }
    if (((token === import36.InfiniteScrollContent) && (44 === requestNodeIndex))) { return this._InfiniteScrollContent_44_4; }
    if (((token === import35.InfiniteScroll) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._InfiniteScroll_42_3; }
    if (((token === import30.Content) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Content_30_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import10.SimpleChange} = (null as any);
    const currVal_3:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._MenuToggle_4_5.menuToggle = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'menu';
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_6_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    changes = (null as any);
    const currVal_9:any = this.context.listType;
    if (import7.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgModel_15_3.model = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import10.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgModel_15_3.ngOnChanges(changes); }
    const currVal_18:any = 'subscriptions';
    if (import7.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._SegmentButton_17_4.value = currVal_18;
      this._expr_18 = currVal_18;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_17_4.ngOnInit(); }
    const currVal_21:any = 'all';
    if (import7.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._SegmentButton_23_4.value = currVal_21;
      this._expr_21 = currVal_21;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SegmentButton_23_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_30_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Refresher_32_3.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RefresherContent_34_4.ngOnInit(); }
    changes = (null as any);
    const currVal_27:any = this.context.trips;
    if (import7.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgFor_39_6.ngForOf = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import10.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    if ((changes !== (null as any))) { this._NgFor_39_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_39_6.ngDoCheck(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._InfiniteScrollContent_44_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4]);
        this._ToolbarItem_4_6._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_SegmentButton_15_0.dirty) {
        this._query_SegmentButton_15_0.reset([
          this._SegmentButton_17_4,
          this._SegmentButton_23_4
        ]
        );
        this._Segment_15_6._buttons = this._query_SegmentButton_15_0;
        this._query_SegmentButton_15_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._InfiniteScroll_42_3.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4._sbPadding;
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.isHidden;
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Toolbar_13_4._sbPadding;
    if (import7.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_13,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this._NgControlStatus_15_5.ngClassUntouched;
    if (import7.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_15,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_15_5.ngClassTouched;
    if (import7.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_15,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_15_5.ngClassPristine;
    if (import7.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_15,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_15_5.ngClassDirty;
    if (import7.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_15,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_15_5.ngClassValid;
    if (import7.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_15,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_15_5.ngClassInvalid;
    if (import7.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_15,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_22:any = this._Content_30_4._sbPadding;
    if (import7.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_30,'statusbar-padding',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_24:any = (this._Refresher_32_3.state !== 'inactive');
    if (import7.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_32,'refresher-active',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._Refresher_32_3._top;
    if (import7.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementStyle(this._el_32,'top',((this.viewUtils.sanitizer.sanitize(import57.SecurityContext.STYLE,currVal_25) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import57.SecurityContext.STYLE,currVal_25).toString()));
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._RefresherContent_34_4.r.state;
    if (import7.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementAttribute(this._el_34,'state',((currVal_26 == (null as any))? (null as any): currVal_26.toString()));
      this._expr_26 = currVal_26;
    }
    const currVal_29:any = this._InfiniteScrollContent_44_4.inf.state;
    if (import7.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementAttribute(this._el_44,'state',((currVal_29 == (null as any))? (null as any): currVal_29.toString()));
      this._expr_29 = currVal_29;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Segment_15_6.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Icon_6_3.ngOnDestroy();
    this._NgModel_15_3.ngOnDestroy();
    this._Refresher_32_3.ngOnDestroy();
    this._InfiniteScroll_42_3.ngOnDestroy();
    this._Content_30_4.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.listType = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_17_0($event:any):boolean {
    this._appEl_17.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.switchListType('subscriptions')) !== false);
    const pd_1:any = ((<any>this._SegmentButton_17_4.onClick()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_click_23_0($event:any):boolean {
    this._appEl_23.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.switchListType('all')) !== false);
    const pd_1:any = ((<any>this._SegmentButton_23_4.onClick()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_ionRefresh_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.refreshTrips($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInfinite_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doInfinite($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TripsPage0(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<import6.TripsPage> {
  if ((renderType_TripsPage === (null as any))) { (renderType_TripsPage = viewUtils.createRenderComponentType('/home/nicolas/projects/cloudtripper/cloudtripper-frontend/.tmp/pages/trips/trips.html',0,import16.ViewEncapsulation.None,styles_TripsPage,{})); }
  return new _View_TripsPage0(viewUtils,parentInjector,declarationEl);
}
class _View_TripsPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import58.Card;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _Badge_13_3:import29.Badge;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _Badge_16_3:import29.Badge;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _Row_22_3:import59.Row;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import60.NgIf;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import60.NgIf;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import60.NgIf;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_TripsPage1,renderType_TripsPage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','card-background-page');
    this.renderer.setElementAttribute(this._el_0,'item-content','');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card',(null as any));
    this._Card_2_3 = new import58.Card(this.parent.parentInjector.get(import37.Config),new import38.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','no-padding');
    this.renderer.setElementAttribute(this._el_4,'outline','');
    this._text_5 = this.renderer.createText(this._el_4,'\n      \n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','card-title');
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','card-subtitle');
    this._text_12 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-badge',(null as any));
    this._Badge_13_3 = new import29.Badge(this.parent.parentInjector.get(import37.Config),new import38.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n          ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_11,'ion-badge',(null as any));
    this._Badge_16_3 = new import29.Badge(this.parent.parentInjector.get(import37.Config),new import38.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_19 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n\n      ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_2,'ion-row',(null as any));
    this._Row_22_3 = new import59.Row();
    this._text_23 = this.renderer.createText(this._el_22,'\n        \n        ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_24 = new import2.AppElement(24,22,this,this._anchor_24);
    this._TemplateRef_24_5 = new import53.TemplateRef_(this._appEl_24,viewFactory_TripsPage2);
    this._NgIf_24_6 = new import60.NgIf(this._appEl_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_26 = new import2.AppElement(26,22,this,this._anchor_26);
    this._TemplateRef_26_5 = new import53.TemplateRef_(this._appEl_26,viewFactory_TripsPage3);
    this._NgIf_26_6 = new import60.NgIf(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_28 = new import2.AppElement(28,22,this,this._anchor_28);
    this._TemplateRef_28_5 = new import53.TemplateRef_(this._appEl_28,viewFactory_TripsPage4);
    this._NgIf_28_6 = new import60.NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._text_30 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this._expr_6 = import10.UNINITIALIZED;
    this._expr_7 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import29.Badge) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Badge_13_3; }
    if (((token === import29.Badge) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Badge_16_3; }
    if (((token === import53.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import60.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6; }
    if (((token === import53.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import60.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6; }
    if (((token === import53.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import60.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6; }
    if (((token === import59.Row) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Row_22_3; }
    if (((token === import58.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Card_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5:boolean = !this.context.$implicit.Subscribed;
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_24_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.context.$implicit.Subscribed;
    if (import7.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_26_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.$implicit.Subscribed;
    if (import7.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_28_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.context.$implicit.Image;
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import57.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import7.interpolate(2,'\n          ',this.context.$implicit.UserName,' in ',this.context.$implicit.Destination,'\n        ');
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_9,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import7.interpolate(1,'',this.context.$implicit.NumberOfLogs,' registros');
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_14,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import7.interpolate(1,'',this.context.$implicit.NumberOfSubscriptions,' suscriptores');
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_17,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.showTripLogs(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_TripsPage1(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TripsPage1(viewUtils,parentInjector,declarationEl);
}
class _View_TripsPage2 extends import1.AppView<any> {
  _el_0:any;
  _Col_0_3:import59.Col;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import20.Button;
  _text_3:any;
  _el_4:any;
  _Icon_4_3:import24.Icon;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_TripsPage2,renderType_TripsPage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this._Col_0_3 = new import59.Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','subscribe-button');
    this.renderer.setElementAttribute(this._el_2,'clear','');
    this.renderer.setElementAttribute(this._el_2,'color','secondary');
    this.renderer.setElementAttribute(this._el_2,'icon-left','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'small','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import42.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import20.Button((null as any),'',this.parent.parent.parentInjector.get(import37.Config),new import38.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_4,'name','add');
    this.renderer.setElementAttribute(this._el_4,'role','img');
    this._Icon_4_3 = new import24.Icon(this.parent.parent.parentInjector.get(import37.Config),new import38.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText((null as any),'\n            Agregar a mis suscripciones\n          ',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._text_3,
        this._el_4,
        this._text_5
      ]
    )],(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (4 === requestNodeIndex))) { return this._Icon_4_3; }
    if (((token === import20.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Button_2_4; }
    if (((token === import59.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Col_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.small = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.clear = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'secondary';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_2_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'add';
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_4_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_5:any = this._Icon_4_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_4,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_4_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.subscribe(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_TripsPage2(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TripsPage2(viewUtils,parentInjector,declarationEl);
}
class _View_TripsPage3 extends import1.AppView<any> {
  _el_0:any;
  _Col_0_3:import59.Col;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import20.Button;
  _text_3:any;
  _el_4:any;
  _Icon_4_3:import24.Icon;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_TripsPage3,renderType_TripsPage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this._Col_0_3 = new import59.Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'clear','');
    this.renderer.setElementAttribute(this._el_2,'color','danger');
    this.renderer.setElementAttribute(this._el_2,'icon-left','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'small','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import42.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import20.Button((null as any),'',this.parent.parent.parentInjector.get(import37.Config),new import38.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_4,'name','close');
    this.renderer.setElementAttribute(this._el_4,'role','img');
    this._Icon_4_3 = new import24.Icon(this.parent.parent.parentInjector.get(import37.Config),new import38.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText((null as any),'\n          Desuscribir\n      ',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._text_3,
        this._el_4,
        this._text_5
      ]
    )],(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this._expr_5 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (4 === requestNodeIndex))) { return this._Icon_4_3; }
    if (((token === import20.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Button_2_4; }
    if (((token === import59.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Col_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.small = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.clear = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'danger';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Button_2_4.color = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_4:any = 'close';
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_4_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_5:any = this._Icon_4_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_4,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_4_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.unsubscribe(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_TripsPage3(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TripsPage3(viewUtils,parentInjector,declarationEl);
}
class _View_TripsPage4 extends import1.AppView<any> {
  _el_0:any;
  _Col_0_3:import59.Col;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Button_2_4:import20.Button;
  _text_3:any;
  _el_4:any;
  _Icon_4_3:import24.Icon;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement) {
    super(_View_TripsPage4,renderType_TripsPage,import9.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import10.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-col',(null as any));
    this._Col_0_3 = new import59.Col();
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'clear','');
    this.renderer.setElementAttribute(this._el_2,'icon-left','');
    this.renderer.setElementAttribute(this._el_2,'ion-button','');
    this.renderer.setElementAttribute(this._el_2,'small','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import42.viewFactory_Button0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Button_2_4 = new import20.Button((null as any),'',this.parent.parent.parentInjector.get(import37.Config),new import38.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Button_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_4,'name','eye');
    this.renderer.setElementAttribute(this._el_4,'role','img');
    this._Icon_4_3 = new import24.Icon(this.parent.parent.parentInjector.get(import37.Config),new import38.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText((null as any),'\n          Detalles\n      ',(null as any));
      compView_2.create(this._Button_2_4,[[].concat([
        this._text_3,
        this._el_4,
        this._text_5
      ]
    )],(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import10.UNINITIALIZED;
    this._expr_2 = import10.UNINITIALIZED;
    this._expr_3 = import10.UNINITIALIZED;
    this._expr_4 = import10.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.Icon) && (4 === requestNodeIndex))) { return this._Icon_4_3; }
    if (((token === import20.Button) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Button_2_4; }
    if (((token === import59.Col) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Col_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Button_2_4.small = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = '';
    if (import7.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._Button_2_4.clear = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    if (changed) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_3:any = 'eye';
    if (import7.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_4_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Button_2_4.ngAfterContentInit(); } }
    const currVal_4:any = this._Icon_4_3._hidden;
    if (import7.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_4,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_4_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.showTripDetails(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_TripsPage4(viewUtils:import7.ViewUtils,parentInjector:import8.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TripsPage4(viewUtils,parentInjector,declarationEl);
}